-- =============================================================================
-- LA PENDA EXPRESS · PASO 6 — Cargar el recetario a una tabla de trabajo
-- business_id = 35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6
--
-- Fuente: "Recetario Estandar de Cocina", edicion Agosto 2026, Eddy Almonte.
-- 130 fichas, 597 lineas de ingrediente, transcritas del PDF.
--
-- ESTO NO CREA RECETAS TODAVIA. Crea una tabla de trabajo y la cruza contra
-- menu_items e inventory_items para ver que empareja y que no. El mapeo es el
-- trabajo real: "Chivo limpio" o "Sofrito criollo" son nombres del papel.
--
-- La tabla se llama _recetario_penda y se borra al final (hay un drop abajo).
--
-- LA COLUMNA `nota` MARCA LO QUE NO SE PUEDE CARGAR TAL CUAL:
--   PLANTILLA    la ficha no tiene ingredientes reales, es el molde vacio
--   PLACEHOLDER  algun ingrediente dice "segun receta" / "elegida" / "del dia"
--   REVISAR      duplicados por copia, o algo que no cuadra
-- =============================================================================

drop table if exists public._recetario_penda;

create table public._recetario_penda (
  codigo       text not null,
  categoria    text not null,
  producto     text not null,
  orden        int  not null,
  ingrediente  text not null,
  cantidad     numeric,
  unidad       text not null,
  nota         text default '',
  primary key (codigo, orden)
);

insert into public._recetario_penda
  (codigo, categoria, producto, orden, ingrediente, cantidad, unidad, nota)
values
  ('PE-DES-001','DESAYUNOS','OMELETTE CON PAN TOSTADO',1,'Huevos enteros',3,'ud',''),
  ('PE-DES-001','DESAYUNOS','OMELETTE CON PAN TOSTADO',2,'Sal y pimienta',2,'g',''),
  ('PE-DES-001','DESAYUNOS','OMELETTE CON PAN TOSTADO',3,'Mantequilla',8,'g',''),
  ('PE-DES-001','DESAYUNOS','OMELETTE CON PAN TOSTADO',4,'Queso',35,'g',''),
  ('PE-DES-001','DESAYUNOS','OMELETTE CON PAN TOSTADO',5,'Pan tostado',2,'rebanada',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',1,'Huevos enteros',3,'ud',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',2,'Sal y pimienta',2,'g',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',3,'Mantequilla',8,'g',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',4,'Queso',35,'g',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',5,'Pan tostado',2,'rebanada',''),
  ('PE-DES-002','DESAYUNOS','OMELETTE CON VEGETALES',6,'Pimientos, cebolla y tomate',70,'g',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',1,'Huevos enteros',3,'ud',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',2,'Sal y pimienta',2,'g',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',3,'Mantequilla',8,'g',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',4,'Queso',35,'g',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',5,'Pan tostado',2,'rebanada',''),
  ('PE-DES-003','DESAYUNOS','OMELETTE CON BACON',6,'Bacon cocido crujiente',35,'g',''),
  ('PE-DES-004','DESAYUNOS','OMELETTE LIGHT',1,'Claras de huevo',5,'ud','REVISAR:el procedimiento menciona queso y pan tostado que NO estan en los ingredientes'),
  ('PE-DES-004','DESAYUNOS','OMELETTE LIGHT',2,'Espinaca',30,'g','REVISAR:el procedimiento menciona queso y pan tostado que NO estan en los ingredientes'),
  ('PE-DES-004','DESAYUNOS','OMELETTE LIGHT',3,'Tomate',35,'g','REVISAR:el procedimiento menciona queso y pan tostado que NO estan en los ingredientes'),
  ('PE-DES-004','DESAYUNOS','OMELETTE LIGHT',4,'Vegetales mixtos',45,'g','REVISAR:el procedimiento menciona queso y pan tostado que NO estan en los ingredientes'),
  ('PE-DES-004','DESAYUNOS','OMELETTE LIGHT',5,'Aceite de oliva',5,'ml','REVISAR:el procedimiento menciona queso y pan tostado que NO estan en los ingredientes'),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',1,'Huevos enteros',3,'ud',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',2,'Sal y pimienta',2,'g',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',3,'Mantequilla',8,'g',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',4,'Queso',35,'g',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',5,'Pan tostado',2,'rebanada',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',6,'Pastrami',55,'g',''),
  ('PE-DES-005','DESAYUNOS','OMELETTE DE PASTRAMI',7,'Cebolla caramelizada',25,'g',''),
  ('PE-DES-006','DESAYUNOS','CROISSANT PLAIN',1,'Croissant de mantequilla',1,'ud',''),
  ('PE-DES-006','DESAYUNOS','CROISSANT PLAIN',2,'Mantequilla',8,'g',''),
  ('PE-DES-007','DESAYUNOS','CROISSANT DE QUESO',1,'Croissant de mantequilla',1,'ud',''),
  ('PE-DES-007','DESAYUNOS','CROISSANT DE QUESO',2,'Queso',60,'g',''),
  ('PE-DES-008','DESAYUNOS','CROISSANT DE JAMON Y QUESO',1,'Croissant de mantequilla',1,'ud',''),
  ('PE-DES-008','DESAYUNOS','CROISSANT DE JAMON Y QUESO',2,'Jamon cocido',45,'g',''),
  ('PE-DES-008','DESAYUNOS','CROISSANT DE JAMON Y QUESO',3,'Queso',45,'g',''),
  ('PE-DES-009','DESAYUNOS','CROISSANT DE NUTELLA',1,'Croissant de mantequilla',1,'ud',''),
  ('PE-DES-009','DESAYUNOS','CROISSANT DE NUTELLA',2,'Crema de avellanas',45,'g',''),
  ('PE-DES-010','DESAYUNOS','PANCAKES',1,'Mezcla para pancakes',120,'g',''),
  ('PE-DES-010','DESAYUNOS','PANCAKES',2,'Leche',90,'ml',''),
  ('PE-DES-010','DESAYUNOS','PANCAKES',3,'Huevo',1,'ud',''),
  ('PE-DES-010','DESAYUNOS','PANCAKES',4,'Mantequilla',12,'g',''),
  ('PE-DES-010','DESAYUNOS','PANCAKES',5,'Syrup',45,'ml',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',1,'Pan artesanal',2,'rebanada',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',2,'Cream cheese',45,'g',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',3,'Aguacate',80,'g',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',4,'Huevo',1,'ud',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',5,'Limon',5,'ml',''),
  ('PE-DES-011','DESAYUNOS','TOSTADA PENDA',6,'Sal y pimienta',2,'g',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',1,'Huevos',2,'ud',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',2,'Bacon',40,'g',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',3,'Salchicha',60,'g',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',4,'Pan tostado',2,'rebanada',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',5,'Papas desayuno',120,'g',''),
  ('PE-DES-012','DESAYUNOS','DESAYUNO AMERICANO',6,'Mantequilla',8,'g',''),
  ('PE-DES-013','DESAYUNOS','LOS 3 GOLPES',1,'Mangu o pure de viveres',220,'g',''),
  ('PE-DES-013','DESAYUNOS','LOS 3 GOLPES',2,'Huevo frito',1,'ud',''),
  ('PE-DES-013','DESAYUNOS','LOS 3 GOLPES',3,'Queso de freir',55,'g',''),
  ('PE-DES-013','DESAYUNOS','LOS 3 GOLPES',4,'Salami dominicano',55,'g',''),
  ('PE-DES-013','DESAYUNOS','LOS 3 GOLPES',5,'Cebolla encurtida',30,'g',''),
  ('PE-ENT-014','ENTRADAS','EMPANADAS DE CATIBIA (SERVICIO)',1,'Discos de yuca/catibia',4,'ud','REVISAR:lleva relleno de pollo Y de queso a la vez?'),
  ('PE-ENT-014','ENTRADAS','EMPANADAS DE CATIBIA (SERVICIO)',2,'Relleno de pollo',90,'g','REVISAR:lleva relleno de pollo Y de queso a la vez?'),
  ('PE-ENT-014','ENTRADAS','EMPANADAS DE CATIBIA (SERVICIO)',3,'Relleno de queso',70,'g','REVISAR:lleva relleno de pollo Y de queso a la vez?'),
  ('PE-ENT-014','ENTRADAS','EMPANADAS DE CATIBIA (SERVICIO)',4,'Aceite para freir',null,'c/n','REVISAR:lleva relleno de pollo Y de queso a la vez?'),
  ('PE-ENT-015','ENTRADAS','QUIPE DE RES',1,'Masa de trigo sazonada',85,'g',''),
  ('PE-ENT-015','ENTRADAS','QUIPE DE RES',2,'Carne de res sazonada',35,'g',''),
  ('PE-ENT-015','ENTRADAS','QUIPE DE RES',3,'Aceite para freir',null,'c/n',''),
  ('PE-ENT-016','ENTRADAS','QUIPE DE POLLO',1,'Masa de trigo sazonada',85,'g',''),
  ('PE-ENT-016','ENTRADAS','QUIPE DE POLLO',2,'Pollo guisado seco',35,'g',''),
  ('PE-ENT-016','ENTRADAS','QUIPE DE POLLO',3,'Aceite para freir',null,'c/n',''),
  ('PE-ENT-017','ENTRADAS','QUIPE DE QUESO DE CABRA',1,'Masa de trigo sazonada',85,'g',''),
  ('PE-ENT-017','ENTRADAS','QUIPE DE QUESO DE CABRA',2,'Queso de cabra y cebolla caramelizada',35,'g',''),
  ('PE-ENT-017','ENTRADAS','QUIPE DE QUESO DE CABRA',3,'Aceite para freir',null,'c/n',''),
  ('PE-ENT-018','ENTRADAS','EMPANADA',1,'Disco de empanada',1,'ud','PLACEHOLDER:Relleno del dia'),
  ('PE-ENT-018','ENTRADAS','EMPANADA',2,'Relleno del dia',65,'g','PLACEHOLDER:Relleno del dia'),
  ('PE-ENT-018','ENTRADAS','EMPANADA',3,'Aceite para freir',null,'c/n','PLACEHOLDER:Relleno del dia'),
  ('PE-ENT-019','ENTRADAS','DEDITOS DE MOZZARELLA',1,'Mozzarella en bastones',180,'g',''),
  ('PE-ENT-019','ENTRADAS','DEDITOS DE MOZZARELLA',2,'Harina',30,'g',''),
  ('PE-ENT-019','ENTRADAS','DEDITOS DE MOZZARELLA',3,'Huevo batido',1,'ud',''),
  ('PE-ENT-019','ENTRADAS','DEDITOS DE MOZZARELLA',4,'Panko',60,'g',''),
  ('PE-ENT-019','ENTRADAS','DEDITOS DE MOZZARELLA',5,'Salsa de la casa',45,'ml',''),
  ('PE-ENT-020','ENTRADAS','CROQUETAS',1,'Croquetas de la casa',6,'ud',''),
  ('PE-ENT-020','ENTRADAS','CROQUETAS',2,'Panko',35,'g',''),
  ('PE-ENT-020','ENTRADAS','CROQUETAS',3,'Aceite para freir',null,'c/n',''),
  ('PE-ENT-020','ENTRADAS','CROQUETAS',4,'Dip',45,'ml',''),
  ('PE-ENT-021','ENTRADAS','ALITAS PENDA',1,'Alitas de pollo',450,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-ENT-021','ENTRADAS','ALITAS PENDA',2,'Sazonador de la casa',8,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-ENT-021','ENTRADAS','ALITAS PENDA',3,'Salsa elegida',90,'ml','PLACEHOLDER:Salsa elegida'),
  ('PE-ENT-021','ENTRADAS','ALITAS PENDA',4,'Vegetales frescos',60,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-ENT-022','ENTRADAS','LONGANIZA CRIOLLA',1,'Longaniza criolla',300,'g',''),
  ('PE-ENT-022','ENTRADAS','LONGANIZA CRIOLLA',2,'Cebolla',60,'g',''),
  ('PE-ENT-022','ENTRADAS','LONGANIZA CRIOLLA',3,'Limon',1,'ud',''),
  ('PE-ENT-022','ENTRADAS','LONGANIZA CRIOLLA',4,'Aceite',8,'ml',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',1,'Jamon y salami',180,'g',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',2,'Quesos variados',180,'g',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',3,'Aceitunas',60,'g',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',4,'Frutas frescas',120,'g',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',5,'Crackers/pan',100,'g',''),
  ('PE-ENT-023','ENTRADAS','TABLA DE FIAMBRES - 2 PERSONAS',6,'Dips',90,'ml',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',1,'Jamon y salami',360,'g',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',2,'Quesos variados',360,'g',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',3,'Aceitunas',120,'g',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',4,'Frutas frescas',240,'g',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',5,'Crackers/pan',200,'g',''),
  ('PE-ENT-024','ENTRADAS','TABLA DE FIAMBRES - 4 PERSONAS',6,'Dips',180,'ml',''),
  ('PE-ENT-025','ENTRADAS','ENSALADA CESAR',1,'Lechuga romana',150,'g',''),
  ('PE-ENT-025','ENTRADAS','ENSALADA CESAR',2,'Aderezo Cesar',55,'ml',''),
  ('PE-ENT-025','ENTRADAS','ENSALADA CESAR',3,'Parmesano',25,'g',''),
  ('PE-ENT-025','ENTRADAS','ENSALADA CESAR',4,'Crutones',40,'g',''),
  ('PE-ENT-025','ENTRADAS','ENSALADA CESAR',5,'Limon',10,'ml',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',1,'Lechuga',100,'g',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',2,'Tomate',70,'g',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',3,'Pepino',60,'g',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',4,'Aceitunas',30,'g',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',5,'Queso feta',45,'g',''),
  ('PE-ENT-026','ENTRADAS','ENSALADA GRIEGA',6,'Vinagreta',35,'ml',''),
  ('PE-PIZ-027','PIZZAS','PIZZA MARGARITA',1,'Masa de pizza 12 in',280,'g',''),
  ('PE-PIZ-027','PIZZAS','PIZZA MARGARITA',2,'Salsa de tomate',90,'g',''),
  ('PE-PIZ-027','PIZZAS','PIZZA MARGARITA',3,'Mozzarella',160,'g',''),
  ('PE-PIZ-027','PIZZAS','PIZZA MARGARITA',4,'Aceite de oliva',8,'ml',''),
  ('PE-PIZ-027','PIZZAS','PIZZA MARGARITA',5,'Albahaca fresca',8,'g',''),
  ('PE-PIZ-028','PIZZAS','PIZZA PEPPERONI',1,'Masa de pizza 12 in',280,'g',''),
  ('PE-PIZ-028','PIZZAS','PIZZA PEPPERONI',2,'Salsa de tomate',90,'g',''),
  ('PE-PIZ-028','PIZZAS','PIZZA PEPPERONI',3,'Mozzarella',160,'g',''),
  ('PE-PIZ-028','PIZZAS','PIZZA PEPPERONI',4,'Aceite de oliva',8,'ml',''),
  ('PE-PIZ-028','PIZZAS','PIZZA PEPPERONI',5,'Pepperoni',80,'g',''),
  ('PE-PIZ-029','PIZZAS','PIZZA JAMON Y QUESO',1,'Masa de pizza 12 in',280,'g',''),
  ('PE-PIZ-029','PIZZAS','PIZZA JAMON Y QUESO',2,'Salsa de tomate',90,'g',''),
  ('PE-PIZ-029','PIZZAS','PIZZA JAMON Y QUESO',3,'Mozzarella',160,'g',''),
  ('PE-PIZ-029','PIZZAS','PIZZA JAMON Y QUESO',4,'Aceite de oliva',8,'ml',''),
  ('PE-PIZ-029','PIZZAS','PIZZA JAMON Y QUESO',5,'Jamon',75,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',1,'Masa de pizza 12 in',280,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',2,'Salsa de tomate',90,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',3,'Mozzarella',160,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',4,'Aceite de oliva',8,'ml',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',5,'Pepperoni',45,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',6,'Jamon',45,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',7,'Bacon',30,'g',''),
  ('PE-PIZ-030','PIZZAS','PIZZA PENDA SUPREMA',8,'Vegetales mixtos',70,'g',''),
  ('PE-INF-031','MENU INFANTIL','MINI CHEESEBURGER',1,'Pan mini burger',1,'ud',''),
  ('PE-INF-031','MENU INFANTIL','MINI CHEESEBURGER',2,'Carne molida',90,'g',''),
  ('PE-INF-031','MENU INFANTIL','MINI CHEESEBURGER',3,'Queso cheddar',1,'lonja',''),
  ('PE-INF-031','MENU INFANTIL','MINI CHEESEBURGER',4,'Papas fritas',100,'g',''),
  ('PE-INF-032','MENU INFANTIL','DEDITOS DE POLLO',1,'Pechuga en tiras',140,'g',''),
  ('PE-INF-032','MENU INFANTIL','DEDITOS DE POLLO',2,'Empanizado',55,'g',''),
  ('PE-INF-032','MENU INFANTIL','DEDITOS DE POLLO',3,'Papas fritas',100,'g',''),
  ('PE-INF-033','MENU INFANTIL','PASTA INFANTIL',1,'Pasta seca',90,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-INF-033','MENU INFANTIL','PASTA INFANTIL',2,'Salsa elegida',120,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-INF-033','MENU INFANTIL','PASTA INFANTIL',3,'Queso rallado',15,'g','PLACEHOLDER:Salsa elegida'),
  ('PE-INF-034','MENU INFANTIL','MINI PIZZA',1,'Masa de pizza 12 in',280,'g','REVISAR:IDENTICA a PE-PIZ-029 (pizza de 12 pulgadas de adulto). 280g de masa para un plato infantil es casi seguro un error de copia'),
  ('PE-INF-034','MENU INFANTIL','MINI PIZZA',2,'Salsa de tomate',90,'g','REVISAR:IDENTICA a PE-PIZ-029 (pizza de 12 pulgadas de adulto). 280g de masa para un plato infantil es casi seguro un error de copia'),
  ('PE-INF-034','MENU INFANTIL','MINI PIZZA',3,'Mozzarella',160,'g','REVISAR:IDENTICA a PE-PIZ-029 (pizza de 12 pulgadas de adulto). 280g de masa para un plato infantil es casi seguro un error de copia'),
  ('PE-INF-034','MENU INFANTIL','MINI PIZZA',4,'Aceite de oliva',8,'ml','REVISAR:IDENTICA a PE-PIZ-029 (pizza de 12 pulgadas de adulto). 280g de masa para un plato infantil es casi seguro un error de copia'),
  ('PE-INF-034','MENU INFANTIL','MINI PIZZA',5,'Jamon',75,'g','REVISAR:IDENTICA a PE-PIZ-029 (pizza de 12 pulgadas de adulto). 280g de masa para un plato infantil es casi seguro un error de copia'),
  ('PE-EWB-035','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN CUADRADO',1,'Producto principal',220,'g','PLANTILLA'),
  ('PE-EWB-035','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN CUADRADO',2,'Sazonador de la casa',5,'g','PLANTILLA'),
  ('PE-EWB-035','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN CUADRADO',3,'Aceite',8,'ml','PLANTILLA'),
  ('PE-EWB-035','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN CUADRADO',4,'Guarnicion',180,'g','PLANTILLA'),
  ('PE-EWB-036','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN BAGUETTE',1,'Producto principal',220,'g','PLANTILLA'),
  ('PE-EWB-036','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN BAGUETTE',2,'Sazonador de la casa',5,'g','PLANTILLA'),
  ('PE-EWB-036','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN BAGUETTE',3,'Aceite',8,'ml','PLANTILLA'),
  ('PE-EWB-036','EMPAREDADOS, WRAPS Y BURGERS','TOSTADA DE QUESO PAN BAGUETTE',4,'Guarnicion',180,'g','PLANTILLA'),
  ('PE-EWB-037','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH DE JAMON Y QUESO',1,'Pan segun receta',1,'porcion',''),
  ('PE-EWB-037','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH DE JAMON Y QUESO',2,'Queso',40,'g',''),
  ('PE-EWB-037','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH DE JAMON Y QUESO',3,'Vegetales',45,'g',''),
  ('PE-EWB-037','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH DE JAMON Y QUESO',4,'Aderezo',25,'ml',''),
  ('PE-EWB-037','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH DE JAMON Y QUESO',5,'Jamon cocido',70,'g',''),
  ('PE-EWB-038','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH ITALIANO',1,'Pan segun receta',1,'porcion',''),
  ('PE-EWB-038','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH ITALIANO',2,'Queso',40,'g',''),
  ('PE-EWB-038','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH ITALIANO',3,'Vegetales',45,'g',''),
  ('PE-EWB-038','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH ITALIANO',4,'Aderezo',25,'ml',''),
  ('PE-EWB-038','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH ITALIANO',5,'Jamon y salami',110,'g',''),
  ('PE-EWB-039','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH PENDA',1,'Pan segun receta',1,'porcion',''),
  ('PE-EWB-039','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH PENDA',2,'Queso',40,'g',''),
  ('PE-EWB-039','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH PENDA',3,'Vegetales',45,'g',''),
  ('PE-EWB-039','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH PENDA',4,'Aderezo',25,'ml',''),
  ('PE-EWB-039','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH PENDA',5,'Pierna horneada',130,'g',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',1,'Pan segun receta',1,'porcion',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',2,'Queso',40,'g',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',3,'Vegetales',45,'g',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',4,'Aderezo',25,'ml',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',5,'Pollo, jamon y bacon',160,'g',''),
  ('PE-EWB-040','EMPAREDADOS, WRAPS Y BURGERS','CLUB SANDWICH',6,'Huevo',1,'ud',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',1,'Pan cubano/baguette',1,'ud',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',2,'Cerdo asado',100,'g',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',3,'Jamon',55,'g',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',4,'Queso suizo',45,'g',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',5,'Pepinillos',25,'g',''),
  ('PE-EWB-041','EMPAREDADOS, WRAPS Y BURGERS','SANDWICH CUBANO',6,'Mostaza',18,'g',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',2,'Queso',35,'g',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',4,'Papas fritas',120,'g',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',5,'Pollo grillado',130,'g',''),
  ('PE-EWB-042','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO CESAR',6,'Aderezo Cesar',35,'ml',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',2,'Queso',35,'g',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',4,'Papas fritas',120,'g',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',5,'Pavo',110,'g',''),
  ('PE-EWB-043','EMPAREDADOS, WRAPS Y BURGERS','WRAP DE PAVO',6,'Aderezo',30,'ml',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',2,'Queso',35,'g',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',4,'Papas fritas',120,'g',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',5,'Pollo, jamon y bacon',150,'g',''),
  ('PE-EWB-044','EMPAREDADOS, WRAPS Y BURGERS','WRAP CLUB',6,'Aderezo',30,'ml',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',2,'Queso',35,'g',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',4,'Papas fritas',120,'g',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',5,'Pollo grillado',130,'g',''),
  ('PE-EWB-045','EMPAREDADOS, WRAPS Y BURGERS','WRAP POLLO BBQ',6,'Salsa BBQ',35,'ml',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',2,'Queso',35,'g',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',4,'Papas fritas',120,'g',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',5,'Jamon y salami',120,'g',''),
  ('PE-EWB-046','EMPAREDADOS, WRAPS Y BURGERS','WRAP ITALIANO',6,'Aderezo italiano',30,'ml',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',1,'Tortilla grande',1,'ud',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',2,'Queso',35,'g',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',3,'Lechuga y tomate',65,'g',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',4,'Papas fritas',120,'g',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',5,'Vegetales grillados',150,'g',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',6,'Aderezo',30,'ml',''),
  ('PE-EWB-047','EMPAREDADOS, WRAPS Y BURGERS','WRAP VEGGIE',7,'Aguacate',60,'g',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',5,'Carne molida',150,'g',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',6,'Queso cheddar',1,'lonja',''),
  ('PE-EWB-048','EMPAREDADOS, WRAPS Y BURGERS','BACON CHEESEBURGER',7,'Bacon crujiente',35,'g',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',5,'Carne molida',150,'g',''),
  ('PE-EWB-049','EMPAREDADOS, WRAPS Y BURGERS','CHEESEBURGER',6,'Queso cheddar',1,'lonja',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',5,'Carne molida',300,'g',''),
  ('PE-EWB-050','EMPAREDADOS, WRAPS Y BURGERS','DOBLE BURGER',6,'Queso cheddar',2,'lonja',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',5,'Carne molida',150,'g',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',6,'Queso cheddar',1,'lonja',''),
  ('PE-EWB-051','EMPAREDADOS, WRAPS Y BURGERS','MADURO BURGER',7,'Platano maduro frito',70,'g',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',5,'Carne molida',150,'g',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',6,'Queso cheddar',1,'lonja',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',7,'Bacon crujiente',35,'g',''),
  ('PE-EWB-052','EMPAREDADOS, WRAPS Y BURGERS','MADURO BACON BURGER',8,'Platano maduro frito',70,'g',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',1,'Pan brioche',1,'ud',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',2,'Lechuga y tomate',55,'g',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',3,'Salsa Penda',30,'ml',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',4,'Papas fritas',150,'g',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',5,'Carne molida',300,'g',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',6,'Queso cheddar',2,'lonja',''),
  ('PE-EWB-053','EMPAREDADOS, WRAPS Y BURGERS','SMASH PENDA BURGER',7,'Cebolla caramelizada',35,'g',''),
  ('PE-PF-054','PLATOS FUERTES','TABLA PENDA - 2 PERSONAS',1,'Carnes mixtas cocidas',450,'g',''),
  ('PE-PF-054','PLATOS FUERTES','TABLA PENDA - 2 PERSONAS',2,'Longaniza',160,'g',''),
  ('PE-PF-054','PLATOS FUERTES','TABLA PENDA - 2 PERSONAS',3,'Frituras variadas',300,'g',''),
  ('PE-PF-054','PLATOS FUERTES','TABLA PENDA - 2 PERSONAS',4,'Tostones o papas',250,'g',''),
  ('PE-PF-054','PLATOS FUERTES','TABLA PENDA - 2 PERSONAS',5,'Salsas',120,'ml',''),
  ('PE-PF-055','PLATOS FUERTES','TABLA PENDA - 4 PERSONAS',1,'Carnes mixtas cocidas',900,'g',''),
  ('PE-PF-055','PLATOS FUERTES','TABLA PENDA - 4 PERSONAS',2,'Longaniza',320,'g',''),
  ('PE-PF-055','PLATOS FUERTES','TABLA PENDA - 4 PERSONAS',3,'Frituras variadas',600,'g',''),
  ('PE-PF-055','PLATOS FUERTES','TABLA PENDA - 4 PERSONAS',4,'Tostones o papas',500,'g',''),
  ('PE-PF-055','PLATOS FUERTES','TABLA PENDA - 4 PERSONAS',5,'Salsas',240,'ml',''),
  ('PE-PF-056','PLATOS FUERTES','CARNE SALADA',1,'Carne de cerdo preparada',300,'g',''),
  ('PE-PF-056','PLATOS FUERTES','CARNE SALADA',2,'Ajo y oregano',5,'g',''),
  ('PE-PF-056','PLATOS FUERTES','CARNE SALADA',3,'Limon',15,'ml',''),
  ('PE-PF-056','PLATOS FUERTES','CARNE SALADA',4,'Aceite',null,'c/n',''),
  ('PE-PF-057','PLATOS FUERTES','CHICHARRON',1,'Carne de cerdo preparada',300,'g','REVISAR:IDENTICA a PE-PF-056 CARNE SALADA'),
  ('PE-PF-057','PLATOS FUERTES','CHICHARRON',2,'Ajo y oregano',5,'g','REVISAR:IDENTICA a PE-PF-056 CARNE SALADA'),
  ('PE-PF-057','PLATOS FUERTES','CHICHARRON',3,'Limon',15,'ml','REVISAR:IDENTICA a PE-PF-056 CARNE SALADA'),
  ('PE-PF-057','PLATOS FUERTES','CHICHARRON',4,'Aceite',null,'c/n','REVISAR:IDENTICA a PE-PF-056 CARNE SALADA'),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',1,'Chicharron crujiente',220,'g',''),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',2,'Cebolla morada',45,'g',''),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',3,'Zumo de limon',45,'ml',''),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',4,'Cilantro',8,'g',''),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',5,'Aji',3,'g',''),
  ('PE-PF-058','PLATOS FUERTES','CEVICHE DE CHICHARRON',6,'Tomate',50,'g',''),
  ('PE-PF-059','PLATOS FUERTES','PECHUGA A LA PLANCHA',1,'Pechuga de pollo',220,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-059','PLATOS FUERTES','PECHUGA A LA PLANCHA',2,'Marinada de la casa',20,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-059','PLATOS FUERTES','PECHUGA A LA PLANCHA',3,'Aceite',8,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-059','PLATOS FUERTES','PECHUGA A LA PLANCHA',4,'Guarnicion elegida',180,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-060','PLATOS FUERTES','PECHUGA A LA CREMA',1,'Pechuga de pollo',220,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-060','PLATOS FUERTES','PECHUGA A LA CREMA',2,'Marinada de la casa',20,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-060','PLATOS FUERTES','PECHUGA A LA CREMA',3,'Aceite',8,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-060','PLATOS FUERTES','PECHUGA A LA CREMA',4,'Guarnicion elegida',180,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-060','PLATOS FUERTES','PECHUGA A LA CREMA',5,'Salsa crema',120,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-061','PLATOS FUERTES','PECHURINA',1,'Pechuga de pollo',220,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-061','PLATOS FUERTES','PECHURINA',2,'Marinada de la casa',20,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-061','PLATOS FUERTES','PECHURINA',3,'Aceite',8,'ml','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-061','PLATOS FUERTES','PECHURINA',4,'Guarnicion elegida',180,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-061','PLATOS FUERTES','PECHURINA',5,'Empanizado',70,'g','PLACEHOLDER:Guarnicion elegida'),
  ('PE-PF-062','PLATOS FUERTES','CHIVO GUISADO',1,'Chivo limpio',320,'g',''),
  ('PE-PF-062','PLATOS FUERTES','CHIVO GUISADO',2,'Sofrito criollo',80,'g',''),
  ('PE-PF-062','PLATOS FUERTES','CHIVO GUISADO',3,'Tomate',60,'g',''),
  ('PE-PF-062','PLATOS FUERTES','CHIVO GUISADO',4,'Caldo',180,'ml',''),
  ('PE-PF-062','PLATOS FUERTES','CHIVO GUISADO',5,'Hierbas y especias',6,'g',''),
  ('PE-PF-063','PLATOS FUERTES','COSTILLAS CONFITADAS',1,'Costilla de cerdo',420,'g',''),
  ('PE-PF-063','PLATOS FUERTES','COSTILLAS CONFITADAS',2,'Marinada seca',10,'g',''),
  ('PE-PF-063','PLATOS FUERTES','COSTILLAS CONFITADAS',3,'Caldo',120,'ml',''),
  ('PE-PF-063','PLATOS FUERTES','COSTILLAS CONFITADAS',4,'Salsa BBQ o honey mustard',90,'ml',''),
  ('PE-PF-064','PLATOS FUERTES','GUINEA A LA CRIOLLA',1,'Guinea porcionada',320,'g',''),
  ('PE-PF-064','PLATOS FUERTES','GUINEA A LA CRIOLLA',2,'Sofrito criollo',80,'g',''),
  ('PE-PF-064','PLATOS FUERTES','GUINEA A LA CRIOLLA',3,'Tomate',60,'g',''),
  ('PE-PF-064','PLATOS FUERTES','GUINEA A LA CRIOLLA',4,'Caldo',180,'ml',''),
  ('PE-PF-064','PLATOS FUERTES','GUINEA A LA CRIOLLA',5,'Hierbas y especias',6,'g',''),
  ('PE-PF-065','PLATOS FUERTES','CODILLO',1,'Codillo de cerdo',420,'g','REVISAR:misma receta que PE-PF-063, solo cambia el corte'),
  ('PE-PF-065','PLATOS FUERTES','CODILLO',2,'Marinada seca',10,'g','REVISAR:misma receta que PE-PF-063, solo cambia el corte'),
  ('PE-PF-065','PLATOS FUERTES','CODILLO',3,'Caldo',120,'ml','REVISAR:misma receta que PE-PF-063, solo cambia el corte'),
  ('PE-PF-065','PLATOS FUERTES','CODILLO',4,'Salsa BBQ o honey mustard',90,'ml','REVISAR:misma receta que PE-PF-063, solo cambia el corte'),
  ('PE-PF-066','PLATOS FUERTES','RABO ENCENDIDO',1,'Rabo de res',320,'g',''),
  ('PE-PF-066','PLATOS FUERTES','RABO ENCENDIDO',2,'Sofrito criollo',80,'g',''),
  ('PE-PF-066','PLATOS FUERTES','RABO ENCENDIDO',3,'Tomate',60,'g',''),
  ('PE-PF-066','PLATOS FUERTES','RABO ENCENDIDO',4,'Caldo',180,'ml',''),
  ('PE-PF-066','PLATOS FUERTES','RABO ENCENDIDO',5,'Hierbas y especias',6,'g',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',1,'Churrasco importado',280,'g',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',3,'Aceite',8,'ml',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',5,'Guarnicion',180,'g',''),
  ('PE-PF-067','PLATOS FUERTES','MAR Y TIERRA',6,'Camarones limpios',140,'g',''),
  ('PE-PF-068','PLATOS FUERTES','FILETE DE CERDO',1,'Filete de cerdo',280,'g',''),
  ('PE-PF-068','PLATOS FUERTES','FILETE DE CERDO',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-068','PLATOS FUERTES','FILETE DE CERDO',3,'Aceite',8,'ml',''),
  ('PE-PF-068','PLATOS FUERTES','FILETE DE CERDO',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-068','PLATOS FUERTES','FILETE DE CERDO',5,'Guarnicion',180,'g',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',1,'Filete mignon',280,'g',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',3,'Aceite',8,'ml',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',5,'Guarnicion',180,'g',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',6,'Bacon',35,'g',''),
  ('PE-PF-069','PLATOS FUERTES','FILETE MIGNON',7,'Salsa de hongos',90,'ml',''),
  ('PE-PF-070','PLATOS FUERTES','RIBEYE',1,'Ribeye',280,'g',''),
  ('PE-PF-070','PLATOS FUERTES','RIBEYE',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-070','PLATOS FUERTES','RIBEYE',3,'Aceite',8,'ml',''),
  ('PE-PF-070','PLATOS FUERTES','RIBEYE',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-070','PLATOS FUERTES','RIBEYE',5,'Guarnicion',180,'g',''),
  ('PE-PF-071','PLATOS FUERTES','PICANHA',1,'Picanha',280,'g',''),
  ('PE-PF-071','PLATOS FUERTES','PICANHA',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-071','PLATOS FUERTES','PICANHA',3,'Aceite',8,'ml',''),
  ('PE-PF-071','PLATOS FUERTES','PICANHA',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-071','PLATOS FUERTES','PICANHA',5,'Guarnicion',180,'g',''),
  ('PE-PF-072','PLATOS FUERTES','CHURRASCO IMPORTADO',1,'Churrasco importado',280,'g',''),
  ('PE-PF-072','PLATOS FUERTES','CHURRASCO IMPORTADO',2,'Sal gruesa y pimienta',5,'g',''),
  ('PE-PF-072','PLATOS FUERTES','CHURRASCO IMPORTADO',3,'Aceite',8,'ml',''),
  ('PE-PF-072','PLATOS FUERTES','CHURRASCO IMPORTADO',4,'Chimichurri o salsa',45,'ml',''),
  ('PE-PF-072','PLATOS FUERTES','CHURRASCO IMPORTADO',5,'Guarnicion',180,'g',''),
  ('PE-PM-073','PESCADOS Y MARISCOS','SALMON AL GRILL',1,'Salmon',220,'g',''),
  ('PE-PM-073','PESCADOS Y MARISCOS','SALMON AL GRILL',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-073','PESCADOS Y MARISCOS','SALMON AL GRILL',3,'Aceite',8,'ml',''),
  ('PE-PM-073','PESCADOS Y MARISCOS','SALMON AL GRILL',4,'Limon',15,'ml',''),
  ('PE-PM-073','PESCADOS Y MARISCOS','SALMON AL GRILL',5,'Guarnicion',180,'g',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',1,'Salmon',220,'g',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',3,'Aceite',8,'ml',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',4,'Limon',15,'ml',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',5,'Guarnicion',180,'g',''),
  ('PE-PM-074','PESCADOS Y MARISCOS','SALMON EN SALSA DE CHINOLA',6,'Salsa de chinola',100,'ml',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',1,'Salmon',220,'g',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',3,'Aceite',8,'ml',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',4,'Limon',15,'ml',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',5,'Guarnicion',180,'g',''),
  ('PE-PM-075','PESCADOS Y MARISCOS','SALMON HOT HONEY',6,'Glaseado hot honey',55,'ml',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',1,'Camarones limpios',240,'g',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',3,'Aceite',8,'ml',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',4,'Limon',15,'ml',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',5,'Guarnicion',180,'g',''),
  ('PE-PM-076','PESCADOS Y MARISCOS','CAMARONES AL AJILLO',6,'Mantequilla de ajo y perejil',70,'g',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',1,'Camarones limpios',240,'g',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',3,'Aceite',8,'ml',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',4,'Limon',15,'ml',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',5,'Guarnicion',180,'g',''),
  ('PE-PM-077','PESCADOS Y MARISCOS','CAMARONES A LA CRIOLLA',6,'Salsa criolla',120,'ml',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',1,'Camarones limpios',240,'g',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',3,'Aceite',8,'ml',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',4,'Limon',15,'ml',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',5,'Guarnicion',180,'g',''),
  ('PE-PM-078','PESCADOS Y MARISCOS','CAMARONES A LA CREMA',6,'Salsa crema de ajo y parmesano',120,'ml',''),
  ('PE-PM-079','PESCADOS Y MARISCOS','MERO A LA PLANCHA',1,'Filete de mero',220,'g',''),
  ('PE-PM-079','PESCADOS Y MARISCOS','MERO A LA PLANCHA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-079','PESCADOS Y MARISCOS','MERO A LA PLANCHA',3,'Aceite',8,'ml',''),
  ('PE-PM-079','PESCADOS Y MARISCOS','MERO A LA PLANCHA',4,'Limon',15,'ml',''),
  ('PE-PM-079','PESCADOS Y MARISCOS','MERO A LA PLANCHA',5,'Guarnicion',180,'g',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',1,'Filete de mero',220,'g',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',3,'Aceite',8,'ml',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',4,'Limon',15,'ml',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',5,'Guarnicion',180,'g',''),
  ('PE-PM-080','PESCADOS Y MARISCOS','MERO AL AJILLO',6,'Mantequilla de ajo y perejil',70,'g',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',1,'Filete de mero',220,'g',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',3,'Aceite',8,'ml',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',4,'Limon',15,'ml',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',5,'Guarnicion',180,'g',''),
  ('PE-PM-081','PESCADOS Y MARISCOS','MERO A LA CRIOLLA',6,'Salsa criolla',120,'ml',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',1,'Filete de mero',220,'g',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',2,'Sal y pimienta',3,'g',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',3,'Aceite',8,'ml',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',4,'Limon',15,'ml',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',5,'Guarnicion',180,'g',''),
  ('PE-PM-082','PESCADOS Y MARISCOS','MERO A LA CREMA',6,'Salsa crema de ajo y parmesano',120,'ml',''),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',1,'Arroz cocido frio',250,'g','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',2,'Proteina segun receta',160,'g','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',3,'Vegetales mixtos',90,'g','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',4,'Salsa de soya',25,'ml','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',5,'Huevo',1,'ud','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-083','ARROCES, PASTAS Y MOFONGOS','ARROZ FRITO PENDA',6,'Aceite',15,'ml','PLACEHOLDER:Proteina segun receta'),
  ('PE-APM-084','ARROCES, PASTAS Y MOFONGOS','ARROZ PENDA FRITO DE MARISCOS',1,'Producto principal',220,'g','PLANTILLA'),
  ('PE-APM-084','ARROCES, PASTAS Y MOFONGOS','ARROZ PENDA FRITO DE MARISCOS',2,'Sazonador de la casa',5,'g','PLANTILLA'),
  ('PE-APM-084','ARROCES, PASTAS Y MOFONGOS','ARROZ PENDA FRITO DE MARISCOS',3,'Aceite',8,'ml','PLANTILLA'),
  ('PE-APM-084','ARROCES, PASTAS Y MOFONGOS','ARROZ PENDA FRITO DE MARISCOS',4,'Guarnicion',180,'g','PLANTILLA'),
  ('PE-APM-085','ARROCES, PASTAS Y MOFONGOS','PASTA 3 QUESOS',1,'Pasta seca',120,'g',''),
  ('PE-APM-085','ARROCES, PASTAS Y MOFONGOS','PASTA 3 QUESOS',2,'Parmesano',20,'g',''),
  ('PE-APM-085','ARROCES, PASTAS Y MOFONGOS','PASTA 3 QUESOS',3,'Agua de coccion',40,'ml',''),
  ('PE-APM-085','ARROCES, PASTAS Y MOFONGOS','PASTA 3 QUESOS',4,'Salsa de mozzarella, gouda y parmesano',180,'g',''),
  ('PE-APM-086','ARROCES, PASTAS Y MOFONGOS','PASTA ALFREDO',1,'Pasta seca',120,'g',''),
  ('PE-APM-086','ARROCES, PASTAS Y MOFONGOS','PASTA ALFREDO',2,'Parmesano',20,'g',''),
  ('PE-APM-086','ARROCES, PASTAS Y MOFONGOS','PASTA ALFREDO',3,'Agua de coccion',40,'ml',''),
  ('PE-APM-086','ARROCES, PASTAS Y MOFONGOS','PASTA ALFREDO',4,'Salsa Alfredo',180,'g',''),
  ('PE-APM-087','ARROCES, PASTAS Y MOFONGOS','PASTA PESTO',1,'Pasta seca',120,'g',''),
  ('PE-APM-087','ARROCES, PASTAS Y MOFONGOS','PASTA PESTO',2,'Parmesano',20,'g',''),
  ('PE-APM-087','ARROCES, PASTAS Y MOFONGOS','PASTA PESTO',3,'Agua de coccion',40,'ml',''),
  ('PE-APM-087','ARROCES, PASTAS Y MOFONGOS','PASTA PESTO',4,'Pesto',70,'g',''),
  ('PE-APM-088','ARROCES, PASTAS Y MOFONGOS','PASTA FRUTTI DI MARE',1,'Pasta seca',120,'g','PLACEHOLDER:Salsa segun receta'),
  ('PE-APM-088','ARROCES, PASTAS Y MOFONGOS','PASTA FRUTTI DI MARE',2,'Parmesano',20,'g','PLACEHOLDER:Salsa segun receta'),
  ('PE-APM-088','ARROCES, PASTAS Y MOFONGOS','PASTA FRUTTI DI MARE',3,'Agua de coccion',40,'ml','PLACEHOLDER:Salsa segun receta'),
  ('PE-APM-088','ARROCES, PASTAS Y MOFONGOS','PASTA FRUTTI DI MARE',4,'Salsa segun receta',180,'g','PLACEHOLDER:Salsa segun receta'),
  ('PE-APM-088','ARROCES, PASTAS Y MOFONGOS','PASTA FRUTTI DI MARE',5,'Mariscos mixtos',180,'g','PLACEHOLDER:Salsa segun receta'),
  ('PE-APM-089','ARROCES, PASTAS Y MOFONGOS','MOFONGO CLASICO DE CHICHARRON',1,'Platano verde frito',260,'g','PLACEHOLDER:Proteina/salsa'),
  ('PE-APM-089','ARROCES, PASTAS Y MOFONGOS','MOFONGO CLASICO DE CHICHARRON',2,'Ajo',8,'g','PLACEHOLDER:Proteina/salsa'),
  ('PE-APM-089','ARROCES, PASTAS Y MOFONGOS','MOFONGO CLASICO DE CHICHARRON',3,'Caldo',60,'ml','PLACEHOLDER:Proteina/salsa'),
  ('PE-APM-089','ARROCES, PASTAS Y MOFONGOS','MOFONGO CLASICO DE CHICHARRON',4,'Chicharron',70,'g','PLACEHOLDER:Proteina/salsa'),
  ('PE-APM-089','ARROCES, PASTAS Y MOFONGOS','MOFONGO CLASICO DE CHICHARRON',5,'Proteina/salsa',150,'g','PLACEHOLDER:Proteina/salsa'),
  ('PE-APM-090','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE POLLO',1,'Platano verde frito',260,'g',''),
  ('PE-APM-090','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE POLLO',2,'Ajo',8,'g',''),
  ('PE-APM-090','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE POLLO',3,'Caldo',60,'ml',''),
  ('PE-APM-090','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE POLLO',4,'Chicharron',70,'g',''),
  ('PE-APM-090','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE POLLO',5,'Pollo guisado',170,'g',''),
  ('PE-APM-091','ARROCES, PASTAS Y MOFONGOS','MOFONGO MIXTO',1,'Platano verde frito',260,'g',''),
  ('PE-APM-091','ARROCES, PASTAS Y MOFONGOS','MOFONGO MIXTO',2,'Ajo',8,'g',''),
  ('PE-APM-091','ARROCES, PASTAS Y MOFONGOS','MOFONGO MIXTO',3,'Caldo',60,'ml',''),
  ('PE-APM-091','ARROCES, PASTAS Y MOFONGOS','MOFONGO MIXTO',4,'Chicharron',70,'g',''),
  ('PE-APM-091','ARROCES, PASTAS Y MOFONGOS','MOFONGO MIXTO',5,'Pollo y cerdo',180,'g',''),
  ('PE-APM-092','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE CAMARONES',1,'Platano verde frito',260,'g',''),
  ('PE-APM-092','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE CAMARONES',2,'Ajo',8,'g',''),
  ('PE-APM-092','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE CAMARONES',3,'Caldo',60,'ml',''),
  ('PE-APM-092','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE CAMARONES',4,'Chicharron',70,'g',''),
  ('PE-APM-092','ARROCES, PASTAS Y MOFONGOS','MOFONGO DE CAMARONES',5,'Camarones en salsa',180,'g',''),
  ('PE-GUA-093','GUARNICIONES','ARROZ BLANCO',1,'Arroz cocido',180,'g',''),
  ('PE-GUA-094','GUARNICIONES','HABICHUELAS GUISADAS',1,'Habichuelas guisadas',180,'g',''),
  ('PE-GUA-095','GUARNICIONES','TOSTONES',1,'Platano verde',1.5,'ud',''),
  ('PE-GUA-096','GUARNICIONES','PAPAS FRITAS',1,'Papas',180,'g',''),
  ('PE-GUA-097','GUARNICIONES','YUQUITAS',1,'Yuca en bastones',180,'g',''),
  ('PE-GUA-098','GUARNICIONES','ENSALADA VERDE',1,'Lechuga, tomate y pepino',150,'g',''),
  ('PE-GUA-098','GUARNICIONES','ENSALADA VERDE',2,'Aderezo',30,'ml',''),
  ('PE-GUA-099','GUARNICIONES','VEGETALES AL GRILL',1,'Vegetales mixtos',180,'g',''),
  ('PE-GUA-099','GUARNICIONES','VEGETALES AL GRILL',2,'Aceite de oliva',8,'ml',''),
  ('PE-GUA-100','GUARNICIONES','VEGETALES SALTEADOS',1,'Vegetales mixtos',180,'g',''),
  ('PE-GUA-100','GUARNICIONES','VEGETALES SALTEADOS',2,'Mantequilla',8,'g',''),
  ('PE-GUA-101','GUARNICIONES','CASABE',1,'Casabe',80,'g',''),
  ('PE-GUA-102','GUARNICIONES','AGUACATE',1,'Aguacate',120,'g',''),
  ('PE-GUA-103','GUARNICIONES','CEPA DE APIO',1,'Cepa de apio cocida',200,'g',''),
  ('PE-GUA-103','GUARNICIONES','CEPA DE APIO',2,'Mantequilla',12,'g',''),
  ('PE-GUA-103','GUARNICIONES','CEPA DE APIO',3,'Leche',30,'ml',''),
  ('PE-CAF-104','CAFES','CAFE',1,'Cafe dominicano o americano',240,'ml',''),
  ('PE-CAF-105','CAFES','EXPRESO',1,'Cafe molido',18,'g',''),
  ('PE-CAF-105','CAFES','EXPRESO',2,'Agua de extraccion',36,'ml',''),
  ('PE-CAF-106','CAFES','CAFE CORTADITO',1,'Espresso',36,'ml',''),
  ('PE-CAF-106','CAFES','CAFE CORTADITO',2,'Leche texturizada',45,'ml',''),
  ('PE-CAF-107','CAFES','CARAMEL MACCHIATO',1,'Espresso',1,'shot','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-107','CAFES','CARAMEL MACCHIATO',2,'Leche o agua',180,'ml','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-107','CAFES','CARAMEL MACCHIATO',3,'Syrup/topping segun receta',20,'ml','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-108','CAFES','LATTE',1,'Espresso',36,'ml',''),
  ('PE-CAF-108','CAFES','LATTE',2,'Leche texturizada',220,'ml',''),
  ('PE-CAF-109','CAFES','MOCHA',1,'Espresso',36,'ml',''),
  ('PE-CAF-109','CAFES','MOCHA',2,'Chocolate',30,'ml',''),
  ('PE-CAF-109','CAFES','MOCHA',3,'Leche texturizada',180,'ml',''),
  ('PE-CAF-110','CAFES','CARAMEL MOCHA',1,'Espresso',36,'ml','REVISAR:IDENTICA a MOCHA y a MOCACCINO. No lleva caramelo'),
  ('PE-CAF-110','CAFES','CARAMEL MOCHA',2,'Chocolate',30,'ml','REVISAR:IDENTICA a MOCHA y a MOCACCINO. No lleva caramelo'),
  ('PE-CAF-110','CAFES','CARAMEL MOCHA',3,'Leche texturizada',180,'ml','REVISAR:IDENTICA a MOCHA y a MOCACCINO. No lleva caramelo'),
  ('PE-CAF-111','CAFES','CAPUCCINO',1,'Espresso',36,'ml',''),
  ('PE-CAF-111','CAFES','CAPUCCINO',2,'Leche texturizada',150,'ml',''),
  ('PE-CAF-111','CAFES','CAPUCCINO',3,'Espuma',40,'ml',''),
  ('PE-CAF-112','CAFES','MOCACCINO',1,'Espresso',36,'ml','REVISAR:IDENTICA a MOCHA y a CARAMEL MOCHA'),
  ('PE-CAF-112','CAFES','MOCACCINO',2,'Chocolate',30,'ml','REVISAR:IDENTICA a MOCHA y a CARAMEL MOCHA'),
  ('PE-CAF-112','CAFES','MOCACCINO',3,'Leche texturizada',180,'ml','REVISAR:IDENTICA a MOCHA y a CARAMEL MOCHA'),
  ('PE-CAF-113','CAFES','MARSHMELLO',1,'Espresso',1,'shot','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-113','CAFES','MARSHMELLO',2,'Leche o agua',180,'ml','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-113','CAFES','MARSHMELLO',3,'Syrup/topping segun receta',20,'ml','PLACEHOLDER:Syrup/topping segun receta'),
  ('PE-CAF-114','CAFES','CAPUCCINO ESPECIAL',1,'Espresso',36,'ml','REVISAR:IDENTICA a CAPUCCINO. Nada la hace especial'),
  ('PE-CAF-114','CAFES','CAPUCCINO ESPECIAL',2,'Leche texturizada',150,'ml','REVISAR:IDENTICA a CAPUCCINO. Nada la hace especial'),
  ('PE-CAF-114','CAFES','CAPUCCINO ESPECIAL',3,'Espuma',40,'ml','REVISAR:IDENTICA a CAPUCCINO. Nada la hace especial'),
  ('PE-CAF-115','CAFES','FRAPPE LA PENDA',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-115','CAFES','FRAPPE LA PENDA',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-115','CAFES','FRAPPE LA PENDA',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-115','CAFES','FRAPPE LA PENDA',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-115','CAFES','FRAPPE LA PENDA',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-116','CAFES','CARAMEL COFFEE FRAPPE',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-116','CAFES','CARAMEL COFFEE FRAPPE',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-116','CAFES','CARAMEL COFFEE FRAPPE',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-116','CAFES','CARAMEL COFFEE FRAPPE',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-116','CAFES','CARAMEL COFFEE FRAPPE',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-117','CAFES','MILKY WAY FRAPPE',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-117','CAFES','MILKY WAY FRAPPE',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-117','CAFES','MILKY WAY FRAPPE',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-117','CAFES','MILKY WAY FRAPPE',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-117','CAFES','MILKY WAY FRAPPE',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-118','CAFES','SNICKERS FRAPPE',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-118','CAFES','SNICKERS FRAPPE',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-118','CAFES','SNICKERS FRAPPE',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-118','CAFES','SNICKERS FRAPPE',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-118','CAFES','SNICKERS FRAPPE',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-119','CAFES','PENDA EXPRESS FRAPPE',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-119','CAFES','PENDA EXPRESS FRAPPE',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-119','CAFES','PENDA EXPRESS FRAPPE',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-119','CAFES','PENDA EXPRESS FRAPPE',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-119','CAFES','PENDA EXPRESS FRAPPE',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-120','CAFES','COOKIES AND CREAM FRAPPE',1,'Espresso frio',36,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-120','CAFES','COOKIES AND CREAM FRAPPE',2,'Leche',160,'ml','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-120','CAFES','COOKIES AND CREAM FRAPPE',3,'Hielo',220,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-120','CAFES','COOKIES AND CREAM FRAPPE',4,'Base frappe',25,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-120','CAFES','COOKIES AND CREAM FRAPPE',5,'Sabor segun receta',35,'g','PLACEHOLDER:Sabor segun receta - los 6 frappes comparten ficha, solo cambia el sabor'),
  ('PE-CAF-121','CAFES','CHOCOLATE CALIENTE LA PENDA',1,'Espresso',1,'shot','REVISAR:un chocolate caliente que lleva un shot de espresso?'),
  ('PE-CAF-121','CAFES','CHOCOLATE CALIENTE LA PENDA',2,'Leche o agua',180,'ml','REVISAR:un chocolate caliente que lleva un shot de espresso?'),
  ('PE-CAF-121','CAFES','CHOCOLATE CALIENTE LA PENDA',3,'Syrup/topping segun receta',20,'ml','REVISAR:un chocolate caliente que lleva un shot de espresso?'),
  ('PE-JYF-122','JUGOS Y FROZEN','LIMONADA FROZEN',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-122','JUGOS Y FROZEN','LIMONADA FROZEN',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-122','JUGOS Y FROZEN','LIMONADA FROZEN',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-122','JUGOS Y FROZEN','LIMONADA FROZEN',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-122','JUGOS Y FROZEN','LIMONADA FROZEN',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-123','JUGOS Y FROZEN','LIMONADA DE COCO',6,'Crema de coco',60,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-124','JUGOS Y FROZEN','FRESA FROZEN',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa - deberia decir pulpa de fresa'),
  ('PE-JYF-124','JUGOS Y FROZEN','FRESA FROZEN',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa - deberia decir pulpa de fresa'),
  ('PE-JYF-124','JUGOS Y FROZEN','FRESA FROZEN',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa - deberia decir pulpa de fresa'),
  ('PE-JYF-124','JUGOS Y FROZEN','FRESA FROZEN',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa - deberia decir pulpa de fresa'),
  ('PE-JYF-124','JUGOS Y FROZEN','FRESA FROZEN',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa - deberia decir pulpa de fresa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-125','JUGOS Y FROZEN','PINA FROZEN',6,'Jugo de pina',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',6,'Crema de coco',60,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-126','JUGOS Y FROZEN','PINA COLADA',7,'Jugo de pina',100,'ml','PLACEHOLDER:Fruta o pulpa'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',1,'Fruta o pulpa',140,'g','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',2,'Agua',100,'ml','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',3,'Hielo',220,'g','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',4,'Syrup simple',20,'ml','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',5,'Zumo de limon',10,'ml','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',6,'Crema de coco',60,'ml','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',7,'Pulpa de chinola',60,'g','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-127','JUGOS Y FROZEN','CHINOLA COLADA',8,'Jugo de pina',100,'ml','PLACEHOLDER:Fruta o pulpa Y pulpa de chinola en la misma ficha'),
  ('PE-JYF-128','JUGOS Y FROZEN','PITAHAYA FROZEN',1,'Pulpa de pitahaya',140,'g',''),
  ('PE-JYF-128','JUGOS Y FROZEN','PITAHAYA FROZEN',2,'Agua',100,'ml',''),
  ('PE-JYF-128','JUGOS Y FROZEN','PITAHAYA FROZEN',3,'Hielo',220,'g',''),
  ('PE-JYF-128','JUGOS Y FROZEN','PITAHAYA FROZEN',4,'Syrup simple',20,'ml',''),
  ('PE-JYF-128','JUGOS Y FROZEN','PITAHAYA FROZEN',5,'Zumo de limon',10,'ml',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',1,'Pulpa de pitahaya',140,'g',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',2,'Agua',100,'ml',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',3,'Hielo',220,'g',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',4,'Syrup simple',20,'ml',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',5,'Zumo de limon',10,'ml',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',6,'Crema de coco',60,'ml',''),
  ('PE-JYF-129','JUGOS Y FROZEN','PITACOLADA',7,'Jugo de pina',100,'ml',''),
  ('PE-JYF-130','JUGOS Y FROZEN','PITANOLA',1,'Pulpa de pitahaya',140,'g','REVISAR:IDENTICA a PITAHAYA FROZEN'),
  ('PE-JYF-130','JUGOS Y FROZEN','PITANOLA',2,'Agua',100,'ml','REVISAR:IDENTICA a PITAHAYA FROZEN'),
  ('PE-JYF-130','JUGOS Y FROZEN','PITANOLA',3,'Hielo',220,'g','REVISAR:IDENTICA a PITAHAYA FROZEN'),
  ('PE-JYF-130','JUGOS Y FROZEN','PITANOLA',4,'Syrup simple',20,'ml','REVISAR:IDENTICA a PITAHAYA FROZEN'),
  ('PE-JYF-130','JUGOS Y FROZEN','PITANOLA',5,'Zumo de limon',10,'ml','REVISAR:IDENTICA a PITAHAYA FROZEN');


-- ═══ A · RESUMEN: qué se puede cargar y qué no ═══════════════════════════════
select
  count(distinct codigo)                                                as fichas,
  count(*)                                                              as lineas,
  count(distinct codigo) filter (where nota like 'PLANTILLA%')          as PLANTILLAS_vacias,
  count(distinct codigo) filter (where nota like 'PLACEHOLDER%')        as con_placeholder,
  count(distinct codigo) filter (where nota like 'REVISAR%')            as a_revisar,
  count(distinct codigo) filter (where nota = '')                       as LIMPIAS,
  count(distinct ingrediente)                                           as ingredientes_distintos
from public._recetario_penda;


-- ═══ B · Las fichas que NO se pueden cargar tal cual ═════════════════════════
--   Esto es lo que hay que resolver con Eddy antes de crear las recetas.
select codigo, categoria, producto, nota
from public._recetario_penda
where nota <> ''
group by codigo, categoria, producto, nota
order by
  case when nota like 'PLANTILLA%' then 1
       when nota like 'REVISAR%'   then 2
       else 3 end,
  codigo;


-- ═══ C · ¿Existe el producto en el menú? ═════════════════════════════════════
--   Empareja por nombre normalizado (sin tildes, sin dobles espacios).
--   Lo que salga sin match hay que casarlo a mano.
create or replace function public._norm(t text) returns text
language sql immutable as $fn$
  select regexp_replace(
           upper(translate(coalesce(t,''),
                 'áéíóúÁÉÍÓÚñÑüÜ', 'aeiouAEIOUnNuU')),
           '\s+', ' ', 'g')
$fn$;

select r.codigo, r.categoria, r.producto,
       m.name                                   as producto_en_el_menu,
       m.is_active,
       m.is_inventory_tracked,
       (m.inventory_item_id is not null)         as tiene_insumo_directo,
       count(*) over (partition by r.codigo)     as ingredientes
from (select distinct codigo, categoria, producto from public._recetario_penda) r
left join public.menu_items m
       on m.business_id = '35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6'
      and public._norm(m.name) = public._norm(r.producto)
order by (m.id is null) desc, r.codigo;


-- ═══ D · LO IMPORTANTE: ¿existe el insumo? ═══════════════════════════════════
--   Cada ingrediente del papel contra inventory_items. Lo que no empareje
--   hay que crearlo o casarlo con el nombre real que ya usan.
select
  r.ingrediente,
  count(distinct r.codigo)                      as en_cuantas_fichas,
  min(r.unidad)                                 as unidad_receta,
  i.name                                        as insumo_en_el_sistema,
  i.unit                                        as unidad_insumo,
  i.cost,
  case
    when i.id is null                           then 'NO EXISTE'
    when min(r.unidad) = i.unit                 then 'ok'
    else 'UNIDAD DISTINTA'
  end                                           as estado
from public._recetario_penda r
left join public.inventory_items i
       on i.business_id = '35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6'
      and coalesce(i.is_active, true)
      and public._norm(i.name) = public._norm(r.ingrediente)
group by r.ingrediente, i.id, i.name, i.unit, i.cost
order by (i.id is null) desc, count(distinct r.codigo) desc;


-- ═══ E · El resumen de D ═════════════════════════════════════════════════════
--   Cuántos ingredientes hay que crear o casar a mano.
with x as (
  select r.ingrediente, i.id as insumo_id, min(r.unidad) as u_receta, i.unit as u_insumo
  from public._recetario_penda r
  left join public.inventory_items i
         on i.business_id = '35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6'
        and coalesce(i.is_active, true)
        and public._norm(i.name) = public._norm(r.ingrediente)
  group by r.ingrediente, i.id, i.unit
)
select
  count(*)                                                as ingredientes_distintos,
  count(*) filter (where insumo_id is not null)            as emparejados,
  count(*) filter (where insumo_id is null)                as SIN_EMPAREJAR,
  count(*) filter (where insumo_id is not null
                     and u_receta is distinct from u_insumo) as unidad_distinta
from x;


-- ═══ F · Candidatos parecidos para los que no emparejaron ════════════════════
--   Sugerencias por similitud, para acelerar el mapeo a mano.
with faltan as (
  select distinct r.ingrediente
  from public._recetario_penda r
  where not exists (
    select 1 from public.inventory_items i
     where i.business_id = '35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6'
       and coalesce(i.is_active, true)
       and public._norm(i.name) = public._norm(r.ingrediente))
)
select f.ingrediente,
       i.name                                as candidato,
       i.unit, i.cost,
       round(similarity(public._norm(i.name), public._norm(f.ingrediente))::numeric, 2) as parecido
from faltan f
join public.inventory_items i
  on i.business_id = '35c5076a-bd85-4a1b-8d1c-ce719c4f9ae6'
 and coalesce(i.is_active, true)
 and similarity(public._norm(i.name), public._norm(f.ingrediente)) > 0.35
order by f.ingrediente, parecido desc;
-- Si falla con "function similarity does not exist":
--   create extension if not exists pg_trgm;
-- Si no se puede instalar, saltar esta consulta: la D ya dice qué falta.


-- ═══ LIMPIEZA (cuando el mapeo esté resuelto) ════════════════════════════════
-- drop table public._recetario_penda;
-- drop function public._norm(text);
