#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera los SQL de carga de catálogo para el negocio 528df61f.
Mismo archivo de origen que el import de fc3065c8 (ECO BAR), pero SIN IMPUESTOS.

Entrada : CSV con columnas
          Codigo del Producto, Descripcion del Producto, Categoria, Costo, Precio
Salidas : scripts/import_products_528df61f.sql
          scripts/seed_business_528df61f_print_areas.sql

Reglas:
  - tax_mode = 'exclusive' para TODOS (es el default de la app; sin impuesto
    enlazado da igual, pero deja el catalogo listo por si se enlaza despues).
  - SIN IMPUESTOS: no toca menu_item_taxes. Decisión del dueño; la factura
    sale con ITBIS 0.00 (menu_item_taxes es la ÚNICA fuente del impuesto).
  - Categorías = columna Categoria (trim), creadas si faltan, orden alfabético.
  - sku = Codigo del Producto. barcode = NULL (ninguno es EAN/UPC).
  - cost = NULL cuando el CSV trae 0.00 (así es como la app crea un producto
    sin costo; 0 se leería como "cuesta cero" y daría margen 100%).
  - Idempotente: match por (business_id, sku). Re-ejecutable.

Uso:
  python3 scripts/build_products_import_528df61f.py ~/Desktop/productos.csv
"""
import csv, sys, os, unicodedata

BID = "528df61f-7136-4591-9e87-ee19f5882037"
MENU_NAME = "MENU PRINCIPAL"
TAXES = ()  # decision del dueno: ningun impuesto enlazado

HERE = os.path.dirname(os.path.abspath(__file__))

# ── Clasificación de área por categoría ──────────────────────────────────────
BAR_CATS = {
    "BEBIDAS S/A", "BITTERS", "CAFE", "CERVEZAS", "CHAMPANE", "CIGARRILLOS",
    "CIGARROS", "COCTELES", "COGNA", "DIGESTIVOS (BOT)", "DIGESTIVOS (TRA)",
    "ESPECIAL DE BEBIDAS (SV)", "ESPUMANTES", "GINEBRA (TRA)", "GINEBRA BOT",
    "LICORES (TRAGO)", "MOD. BEBIDAS", "PROSECO", "RONES (BOT)", "RONES (TRA)",
    "TEQUILA (BOT)", "TEQUILA (TRA)", "VINOS (BOT X COPA)", "VINOS (COPA)",
    "VINOS BLANCOS (BOT)", "VINOS ROSADOS (BOT)", "VINOS TINTOS (BOT)",
    "VODKA BOT", "VODKA TRA", "WHISKY (BOT)", "WHISKY (TRA)",
}
KITCHEN_CATS = {
    "ALMUERZO SEMANAL", "BRUNCH", "CORTES DE CARNE (SV)", "DIA DE LA MADRES",
    "ENSALADAS", "ENTERADAS DP", "ENTRADAS", "ENTRADAS (SV)", "EXTRAS",
    "FUERTES ESPECIALES (SV)", "GUARNICIONES", "GUARNICIONES (SV)",
    "MENU DIAS DE LAS  MADRES", "MENU NIÑO", "MOD. PLATOS", "PLATO FUERTE",
    "PLATO FUERTE DP", "POSTRES", "POSTRES (SV)", "POSTRES DP",
    "SUSHI ROLL DP",
}
# Categorías de ofertas / días temáticos: mezclan comida y bebida, se rutean
# producto por producto (abajo). Si un sku de estas categorías no aparece en
# OVERRIDES el generador aborta, para que nada quede sin área por descuido.
MIXED_CATS = {
    "OFERTAS HXH", "OFERTAS HH VIERNES", "LUNES UNIVERSITARIOS",
    "MARTES TACOS TUESDAY", "MIERCOLES DE ANTOJO", "JUEVES DE ENCENDIDA",
    "SABADOS BOHEMIOS",
}
# sku -> áreas ("K" cocina, "B" bar, "KB" ambas: el combo imprime en las dos)
OVERRIDES = {
    # OFERTAS HXH
    "0000256": "B",   # ECO MARGARITA 2X1
    "50101": "B",     # 2X1 MOSCOW MULE
    "50102": "B",     # 2X1 ECO SPECIAL
    "50103": "B",     # 2X1 COSTA AZUL
    "50104": "KB",    # ALITAS A LA BBQ X BUDWEISER
    "50105": "B",     # 3X2 EN CORONA
    "50106": "B",     # 2X1 DOBLE RESERVAS TRA
    "5061":  "B",     # 3X2 ECO SANGRIA
    "600444": "K",    # PAELLA DE MARISCOS
    "60104": "B",     # 3X2 GIN TONIC BEFFEATER BLANCA
    "60105": "B",     # OFERTA CERVESAS COORS LIGHTS 2X1
    "60106": "B",     # 2X1 MOJITOS
    "60107": "KB",    # COMBO ALITAS LIDOM + HEINIKEN
    "60108": "KB",    # COMBO LIDOM BURGER + HEINIKEN
    "60109": "K",     # TACOS TUESDAY
    "60110": "KB",    # EL CORO TACOS + CORONA TUESDAY
    "60111": "KB",    # ECO SUSHI + BUZZ BALL
    # LUNES UNIVERSITARIOS
    "90101": "K",     # 2X1 CALAMARES A LA ROMANA
    "90102": "B",     # 2X1 COSTA AZUL
    # MARTES TACOS TUESDAY
    "90201": "K",     # TACOS UNIDAD
    "90202": "KB",    # CORO TACOS + HENIKEN
    "90203": "B",     # 2X1 ECOMARGARITAS
    # MIERCOLES DE ANTOJO
    "90501": "K",     # 2X1 EN TRIO DE MINI BURGUERS
    "90502": "B",     # 2X1 MOSCOW MULE
    # JUEVES DE ENCENDIDA
    "90401": "K",     # 2X1 DUMPLINGS 3 UNIDADES
    "90402": "B",     # 2X1 VODKA CINNAMON
    # OFERTAS HH VIERNES
    "905001": "K",    # 2X1 ECOQUESADILLA
    "905002": "B",    # 2X1 APEROL SPRITZ
    # SABADOS BOHEMIOS
    "90701": "K",     # 2X1 DEDOS DE PESCADOS CON AROS DE CEBOLLAS
    "90702": "B",     # 2X1 COPA DE VINO DE LA CASA
    "90703": "K",     # 2X1 EN CAMARONES MARGARITA
    "90704": "B",     # 2X1 GINTONI BEEFEATE
    # Mal clasificados en el archivo de origen
    "2030":  "B",     # EXTRA GINEBRA CASA  (viene en EXTRAS)
    "20009": "K",     # PICADERAS DE EMBUTIDOS (viene en ESPUMANTES)
}


def q(s):
    if s is None or s == "":
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def num(x):
    return "NULL" if x is None else ("%.2f" % float(x))


def area_of(sku, cat):
    if sku in OVERRIDES:
        return OVERRIDES[sku]
    if cat in BAR_CATS:
        return "B"
    if cat in KITCHEN_CATS:
        return "K"
    if cat in MIXED_CATS:
        raise SystemExit(
            "sku %r (%s) es de categoría mixta y no tiene override de área" % (sku, cat)
        )
    raise SystemExit("categoría sin clasificar: %r (sku %s)" % (cat, sku))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/Desktop/productos.csv")
    with open(src, encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh))

    items = []
    for r in rows:
        sku = (r["Codigo del Producto"] or "").strip()
        name = (r["Descripcion del Producto"] or "").strip()
        cat = (r["Categoria"] or "").strip()
        cost = float(r["Costo"] or 0)
        price = float(r["Precio"] or 0)
        if not sku or not name:
            continue
        items.append({
            "sku": sku,
            "name": unicodedata.normalize("NFC", name),
            "cat": unicodedata.normalize("NFC", cat) or None,
            "cost": cost if cost > 0 else None,   # 0.00 -> NULL (sin costo)
            "price": price,
            "area": area_of(sku, cat),
        })

    dups = {i["sku"] for i in items}
    if len(dups) != len(items):
        raise SystemExit("hay SKUs duplicados en el CSV")

    cats = sorted({i["cat"] for i in items if i["cat"]})
    n_bar = sum(1 for i in items if "B" in i["area"])
    n_kit = sum(1 for i in items if "K" in i["area"])
    n_both = sum(1 for i in items if i["area"] == "KB")

    _write_diag()
    _write_rollback(items)
    _write_import(items, cats, src)
    _write_areas(items, n_bar, n_kit, n_both)
    _write_compare(items)
    _write_resumen(items)

    print("productos : %d" % len(items), file=sys.stderr)
    print("categorias: %d" % len(cats), file=sys.stderr)
    print("bar %d | cocina %d | ambas %d" % (n_bar, n_kit, n_both), file=sys.stderr)
    print("sin precio: %d" % sum(1 for i in items if i["price"] == 0), file=sys.stderr)
    print("sin costo : %d" % sum(1 for i in items if i["cost"] is None), file=sys.stderr)


# ─────────────────────────────────────────────────────────────────────────────
def _write_diag():
    """Preflight: NO escribe nada. Dice como esta el negocio antes de cargar."""
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- DIAGNOSTICO PREVIO — Business %s" % BID)
    w("-- NO ESCRIBE NADA. Correr ANTES de import_products_528df61f.sql.")
    w("--")
    w("-- Que mirar en cada resultado:")
    w("--   1. El negocio existe y es el que crees. inventory_mode y")
    w("--      service_fee_enabled son informativos: este import no los toca.")
    w("--   2. print_areas — hacen falta un area de COCINA y una de BARRA. Sus")
    w("--      `code` van copiados en seed_business_528df61f_print_areas.sql. Si no")
    w("--      existen, crealas primero desde Ajustes -> Areas de impresion; un")
    w("--      area con 0 impresoras acepta el producto pero la comanda no sale.")
    w("--   3. Catalogo actual — con 0 productos el import entra limpio. Si ya hay,")
    w("--      corre COMPARAR_catalogo_528df61f.sql para ver que se actualiza.")
    w("--   4. Menus — si no hay ninguno activo, el import crea 'MENU PRINCIPAL'.")
    w("--   5. Impuestos — informativo. Este import NO enlaza ninguno, a proposito.")
    w("-- =============================================================================")
    w("")
    w("-- 1) El negocio")
    w("select b.id, b.business_name, b.branch_name, b.business_type, b.domain,")
    w("       b.status, bs.inventory_mode, bs.service_fee_enabled")
    w("from public.businesses b")
    w("left join public.business_settings bs on bs.business_id = b.id")
    w("where b.id = '%s'::uuid;" % BID)
    w("")
    w("-- 2) Areas de impresion — de aqui salen los `code` del script de areas")
    w("select a.code, a.name, a.is_active,")
    w("       (select count(*) from public.print_area_printers pp")
    w("         where pp.area_id = a.id) as impresoras")
    w("from public.print_areas a")
    w("where a.business_id = '%s'::uuid" % BID)
    w("order by a.code;")
    w("")
    w("-- 3) Catalogo actual")
    w("select count(*) as productos,")
    w("       count(*) filter (where mi.sku is not null and btrim(mi.sku) <> '') as con_sku,")
    w("       count(*) filter (where mi.is_active) as activos,")
    w("       count(*) filter (where mi.tax_mode = 'inclusive') as inclusive,")
    w("       (select count(*) from public.categories c")
    w("         where c.business_id = '%s'::uuid) as categorias" % BID)
    w("from public.menu_items mi")
    w("where mi.business_id = '%s'::uuid;" % BID)
    w("")
    w("-- 4) Menus")
    w("select m.id, m.name, m.is_active,")
    w("       (select count(*) from public.menu_item_links l where l.menu_id = m.id) as items")
    w("from public.menus m")
    w("where m.business_id = '%s'::uuid" % BID)
    w("order by m.created_at;")
    w("")
    w("-- 5) Impuestos del negocio (informativo: NO se enlaza ninguno)")
    w("select t.name, t.rate, t.is_active,")
    w("       (select count(*) from public.menu_item_taxes x")
    w("          join public.menu_items mi on mi.id = x.item_id")
    w("         where x.tax_id = t.id and mi.business_id = t.business_id) as productos_enlazados")
    w("from public.taxes t")
    w("where t.business_id = '%s'::uuid" % BID)
    w("order by t.name;")
    w("")
    _out("DIAGNOSTICO_528df61f.sql", o)


def _write_rollback(items):
    """Deshace el import: borra SOLO los 625 productos del archivo."""
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- ROLLBACK del import — Business %s" % BID)
    w("--")
    w("-- Borra los %d productos que metio import_products_528df61f.sql, y NADA mas:" % len(items))
    w("-- el filtro es la lista de sku del archivo, asi que un producto que hayas")
    w("-- creado a mano despues no se toca.")
    w("--")
    w("-- SE VA EN CASCADA CON EL PRODUCTO (no hay que borrarlo aparte):")
    w("--   menu_item_links (el menu), menu_item_print_areas (el ruteo N:M),")
    w("--   menu_item_taxes, menu_item_groups, recipes.")
    w("--")
    w("-- LO QUE PUEDE BLOQUEAR EL BORRADO — a proposito, no es un error del script:")
    w("--   order_items.product_id  -> ON DELETE RESTRICT. Si el producto YA SE")
    w("--     VENDIO, Postgres aborta todo. Un producto con historial no se borra,")
    w("--     se DESACTIVA (abajo esta la alternativa).")
    w("--   combo_group_items.menu_item_id -> ON DELETE RESTRICT.")
    w("--   El paso 1 te dice si hay algo de eso ANTES de borrar.")
    w("--")
    w("-- CORRER POR PARTES, EN ORDEN. El paso 1 no escribe nada.")
    w("-- =============================================================================")
    w("")
    w("")
    w("-- ###########################################################################")
    w("-- PASO 1 — QUE SE VA A BORRAR (no escribe nada). Corre esto primero.")
    w("-- ###########################################################################")
    w("begin;")
    w("")
    w("create temp table _sku (sku text primary key) on commit drop;")
    w("insert into _sku (sku) values")
    w(",\n".join("  (%s)" % q(i["sku"]) for i in items) + ";")
    w("")
    w("select")
    w("  (select count(*) from public.menu_items mi")
    w("    where mi.business_id = '%s'::uuid) as productos_del_negocio," % BID)
    w("  (select count(*) from public.menu_items mi join _sku s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid) as se_borrarian," % BID)
    w("  (select count(*) from public.menu_items mi")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and not exists (select 1 from _sku s where s.sku = mi.sku)) as se_quedarian,")
    w("  (select count(*) from public.order_items oi")
    w("     join public.menu_items mi on mi.id = oi.product_id")
    w("     join _sku s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid) as lineas_de_venta_que_bloquean," % BID)
    w("  (select count(*) from public.categories c")
    w("    where c.business_id = '%s'::uuid) as categorias_del_negocio;" % BID)
    w("")
    w("-- Si `lineas_de_venta_que_bloquean` > 0, estos son los culpables.")
    w("-- Esos productos NO se pueden borrar: hay que desactivarlos (paso 2-B).")
    w("select mi.sku, mi.name, count(*) as veces_vendido")
    w("from public.menu_items mi")
    w("join _sku s on s.sku = mi.sku")
    w("join public.order_items oi on oi.product_id = mi.id")
    w("where mi.business_id = '%s'::uuid" % BID)
    w("group by mi.sku, mi.name")
    w("order by count(*) desc, mi.name;")
    w("")
    w("commit;")
    w("")
    w("")
    w("-- ###########################################################################")
    w("-- PASO 2-A — BORRAR. Solo si el paso 1 dio lineas_de_venta_que_bloquean = 0.")
    w("--            Todo en UNA transaccion: si algo falla, no borra nada.")
    w("-- ###########################################################################")
    w("begin;")
    w("")
    w("create temp table _sku (sku text primary key) on commit drop;")
    w("insert into _sku (sku) values")
    w(",\n".join("  (%s)" % q(i["sku"]) for i in items) + ";")
    w("")
    w("delete from public.menu_items mi")
    w("using _sku s")
    w("where mi.sku = s.sku")
    w("  and mi.business_id = '%s'::uuid;" % BID)
    w("")
    w("-- Control: productos_restantes debe ser 0 si el negocio estaba vacio antes")
    w("-- del import (que es el caso: el import reporto actualizados = 0).")
    w("select")
    w("  (select count(*) from public.menu_items")
    w("    where business_id = '%s'::uuid) as productos_restantes," % BID)
    w("  (select count(*) from public.menu_item_links l")
    w("     join public.menu_items mi on mi.id = l.item_id")
    w("    where mi.business_id = '%s'::uuid) as links_restantes," % BID)
    w("  (select count(*) from public.menu_item_print_areas x")
    w("     join public.menu_items mi on mi.id = x.menu_item_id")
    w("    where mi.business_id = '%s'::uuid) as rutas_restantes;" % BID)
    w("")
    w("commit;")
    w("")
    w("")
    w("-- ###########################################################################")
    w("-- PASO 2-B — ALTERNATIVA, solo si el paso 1 encontro ventas.")
    w("--            No borra: desactiva. El producto sale de la caja pero el")
    w("--            historico de ventas y las facturas siguen enteros.")
    w("--            (Descomenta para usarlo.)")
    w("-- ###########################################################################")
    w("-- begin;")
    w("-- create temp table _sku (sku text primary key) on commit drop;")
    w("-- insert into _sku (sku) values ('PEGA', 'AQUI', 'LA', 'LISTA');  -- ver paso 1")
    w("-- update public.menu_items mi")
    w("--   set is_active = false, updated_at = now()")
    w("--   from _sku s")
    w("--  where mi.sku = s.sku and mi.business_id = '%s'::uuid;" % BID)
    w("-- commit;")
    w("")
    w("")
    w("-- ###########################################################################")
    w("-- PASO 3 (OPCIONAL) — las %d categorias que creo el import." % len(sorted({i["cat"] for i in items if i["cat"]})))
    w("--   Solo borra las que quedaron VACIAS. Si vas a subir otro archivo con")
    w("--   las mismas categorias, no corras esto: se reusan solas.")
    w("-- ###########################################################################")
    w("-- begin;")
    w("-- delete from public.categories c")
    w("--  where c.business_id = '%s'::uuid" % BID)
    w("--    and not exists (select 1 from public.menu_items mi where mi.category_id = c.id);")
    w("-- select count(*) as categorias_restantes from public.categories")
    w("--  where business_id = '%s'::uuid;" % BID)
    w("-- commit;")
    w("")
    w("")
    w("-- ###########################################################################")
    w("-- PASO 4 (OPCIONAL) — el menu '%s' que creo el import." % MENU_NAME)
    w("--   Solo si quedo SIN productos. Normalmente conviene dejarlo: el proximo")
    w("--   import lo reusa en vez de crear otro.")
    w("-- ###########################################################################")
    w("-- begin;")
    w("-- delete from public.menus m")
    w("--  where m.business_id = '%s'::uuid" % BID)
    w("--    and m.name = %s" % q(MENU_NAME))
    w("--    and not exists (select 1 from public.menu_item_links l where l.menu_id = m.id);")
    w("-- commit;")
    w("")
    _out("ROLLBACK_import_528df61f.sql", o)


def _write_import(items, cats, src):
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- Carga de catalogo — Business %s" % BID)
    w("--")
    w("-- Origen : %s" % os.path.basename(src))
    w("-- Genera : scripts/build_products_import_528df61f.py  (NO editar a mano)")
    w("--")
    w("--   %d productos | %d categorias" % (len(items), len(cats)))
    w("--   tax_mode = 'exclusive' (impuestos POR FUERA del precio).")
    w("--   SIN IMPUESTOS: no se escribe nada en menu_item_taxes. La factura sale")
    w("--   con ITBIS 0.00 — decision del dueno, no un descuido.")
    w("--")
    w("-- ANTI-DUPLICADOS — el match NO es por sku: si el negocio ya tuviera algun")
    w("-- producto cargado a mano, no traeria sku y se duplicarian. Se hace por")
    w("-- NOMBRE normalizado (mayusculas, sin acentos, espacios colapsados) con")
    w("-- tres reglas. Con el catalogo vacio todo cae en la regla B y entra limpio:")
    w("--")
    w("--   A. Nombre que existe UNA sola vez en el archivo y UNA sola vez en el")
    w("--      catalogo  ->  ACTUALIZA la fila existente y le graba el sku.")
    w("--   B. Nombre que NO existe en el catalogo                ->  INSERTA nuevo.")
    w("--   C. Nombre ambiguo (repetido de un lado o del otro)    ->  NO SE TOCA.")
    w("--      Se lista al final para que lo resuelvas a mano. Preferimos dejarlo")
    w("--      pendiente antes que adivinar y duplicar.")
    w("--")
    w("--   Por construccion NUNCA se inserta un producto cuyo nombre ya este en el")
    w("--   catalogo. Corre scripts/COMPARAR_catalogo_528df61f.sql antes para ver")
    w("--   exactamente que va a pasar con cada uno.")
    w("--")
    w("-- IDEMPOTENTE: re-ejecutarlo no duplica (la 2a vez ya matchea por sku y por")
    w("-- nombre). Todo en UNA transaccion: si algo falla, no queda nada.")
    w("--")
    w("-- DESPUES corre scripts/seed_business_528df61f_print_areas.sql, si no los")
    w("-- productos quedan sin area y \"Enviar a cocina\" falla.")
    w("--")
    w("-- Correr en Supabase Studio -> SQL Editor.")
    w("-- =============================================================================")
    w("")
    w("begin;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 0) SIN IMPUESTOS — decision del dueno (2026-09-05): NINGUN producto")
    w("--    lleva impuesto. Este script no escribe una sola fila en")
    w("--    menu_item_taxes, que es la UNICA fuente del impuesto por producto:")
    w("--    sin vinculo la factura sale con ITBIS 0.00 ante la DGII. Es a")
    w("--    proposito. Si algun dia se quiere el ITBIS, se enlaza aparte.")
    w("--")
    w("--    OJO CON EL PRECIO: los precios del archivo vienen NETOS (sin ITBIS)")
    w("--    — 379.66 x 1.18 = 448.00, 216.95 x 1.18 = 256.00, etc. Sin impuesto")
    w("--    enlazado el cliente paga el neto: 448 se cobra como 379.66.")
    w("-- ---------------------------------------------------------------------------")
    w("do $$")
    w("declare")
    w("  v_business uuid := '%s';" % BID)
    w("begin")
    w("  if not exists (select 1 from public.businesses b where b.id = v_business) then")
    w("    raise exception 'El negocio % no existe', v_business;")
    w("  end if;")
    w("end $$;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 1) Categorias (crea solo las que falten; respeta las existentes)")
    w("-- ---------------------------------------------------------------------------")
    w("insert into public.categories (id, business_id, name, position, is_active)")
    w("select gen_random_uuid(), '%s'::uuid, v.name, v.pos, true" % BID)
    w("from (values")
    w(",\n".join("  (%s, %d)" % (q(c), i) for i, c in enumerate(cats, start=1)))
    w(") as v(name, pos)")
    w("where not exists (")
    w("  select 1 from public.categories c")
    w("  where c.business_id = '%s'::uuid and c.name = v.name" % BID)
    w(");")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 2) El archivo, con clave de match normalizada")
    w("-- ---------------------------------------------------------------------------")
    w("create temp table _stage (")
    w("  sku text primary key, name text, cat text, price numeric, cost numeric")
    w(") on commit drop;")
    w("")
    w("insert into _stage (sku, name, cat, price, cost) values")
    w(",\n".join(
        "  (%s, %s, %s, %s, %s)" % (q(i["sku"]), q(i["name"]), q(i["cat"]),
                                    num(i["price"]), num(i["cost"]))
        for i in items) + ";")
    w("")
    w("create temp table _arch on commit drop as")
    w("select s.*, %s as k from _stage s;" % (NORM % "s.name"))
    w("create index on _arch (k);")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 3) El catalogo actual, con la misma clave")
    w("-- ---------------------------------------------------------------------------")
    w("create temp table _actual on commit drop as")
    w("select mi.id, mi.name, mi.sku, %s as k" % (NORM % "mi.name"))
    w("from public.menu_items mi")
    w("where mi.business_id = '%s'::uuid;" % BID)
    w("create index on _actual (k);")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 4) Regla A — emparejamiento 1:1 sin ambiguedad")
    w("-- ---------------------------------------------------------------------------")
    w("create temp table _match on commit drop as")
    w("select a.sku, x.id as item_id")
    w("from _arch a")
    w("join _actual x on x.k = a.k")
    w("where (select count(*) from _arch   a2 where a2.k = a.k) = 1")
    w("  and (select count(*) from _actual x2 where x2.k = a.k) = 1;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 5) ACTUALIZA los emparejados y les graba el sku del archivo")
    w("-- ---------------------------------------------------------------------------")
    w("update public.menu_items mi")
    w("set sku         = s.sku,")
    w("    name        = s.name,")
    w("    price       = s.price,")
    w("    cost        = s.cost,")
    w("    category_id = c.id,")
    w("    tax_mode    = 'exclusive',")
    w("    is_active   = true,")
    w("    updated_at  = now()")
    w("from _match m")
    w("join _stage s on s.sku = m.sku")
    w("left join lateral (")
    w("  select c2.id from public.categories c2")
    w("  where c2.business_id = '%s'::uuid and c2.name = s.cat" % BID)
    w("  order by c2.created_at asc limit 1")
    w(") c on true")
    w("where mi.id = m.item_id;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 6) Regla B — INSERTA solo los nombres que NO existen en el catalogo.")
    w("--    Este `not exists` es el candado anti-duplicados.")
    w("-- ---------------------------------------------------------------------------")
    w("insert into public.menu_items")
    w("  (business_id, category_id, name, price, cost, tax_mode, sku, is_active)")
    w("select '%s'::uuid, c.id, a.name, a.price, a.cost, 'exclusive', a.sku, true" % BID)
    w("from _arch a")
    w("left join lateral (")
    w("  select c2.id from public.categories c2")
    w("  where c2.business_id = '%s'::uuid and c2.name = a.cat" % BID)
    w("  order by c2.created_at asc limit 1")
    w(") c on true")
    w("where not exists (select 1 from _actual x where x.k = a.k);")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 7) Menu: usa el que ya tiene el negocio ('Menu Principal'); si no hubiera")
    w("--    ninguno, crea uno. Sin fila en menu_item_links no aparece en la caja.")
    w("-- ---------------------------------------------------------------------------")
    w("insert into public.menus (id, business_id, name, is_active)")
    w("select gen_random_uuid(), '%s'::uuid, %s, true" % (BID, q(MENU_NAME)))
    w("where not exists (")
    w("  select 1 from public.menus m")
    w("  where m.business_id = '%s'::uuid and coalesce(m.is_active, true)" % BID)
    w(");")
    w("")
    w("insert into public.menu_item_links (menu_id, item_id, position)")
    w("select m.id, mi.id,")
    w("       row_number() over (order by c.position nulls last, mi.name)")
    w("from public.menu_items mi")
    w("join _stage s on s.sku = mi.sku")
    w("left join public.categories c on c.id = mi.category_id")
    w("join lateral (")
    w("  select m2.id from public.menus m2")
    w("  where m2.business_id = mi.business_id and coalesce(m2.is_active, true)")
    w("  order by m2.created_at asc limit 1")
    w(") m on true")
    w("where mi.business_id = '%s'::uuid" % BID)
    w("  and not exists (")
    w("    select 1 from public.menu_item_links l")
    w("    where l.item_id = mi.id and l.menu_id = m.id")
    w("  );")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 8) Control")
    w("--    en_archivo debe ser %d. con_impuesto / sin_categoria / fuera_del_menu" % len(items))
    w("--    / no_exclusive deben dar 0.")
    w("--    ambiguos_sin_tocar = los de la regla C: se listan en el paso 9.")
    w("-- ---------------------------------------------------------------------------")
    w("select")
    w("  (select count(*) from _arch)  as en_archivo,")
    w("  (select count(*) from _match) as actualizados,")
    w("  (select count(*) from _arch a")
    w("    where not exists (select 1 from _actual x where x.k = a.k)) as insertados,")
    w("  (select count(*) from _arch a")
    w("    where not exists (select 1 from _match m where m.sku = a.sku)")
    w("      and exists (select 1 from _actual x where x.k = a.k)) as ambiguos_sin_tocar,")
    w("  (select count(*) from public.menu_items")
    w("    where business_id = '%s'::uuid) as total_catalogo," % BID)
    w("  (select count(*) from public.categories")
    w("    where business_id = '%s'::uuid) as categorias," % BID)
    w("  (select count(*) from public.menu_items mi join _stage s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid and mi.tax_mode <> 'exclusive') as no_exclusive," % BID)
    w("  (select count(*) from public.menu_items mi join _stage s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and exists (select 1 from public.menu_item_taxes x where x.item_id = mi.id)")
    w("   ) as con_impuesto,")
    w("  (select count(*) from public.menu_items mi join _stage s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid and mi.category_id is null) as sin_categoria," % BID)
    w("  (select count(*) from public.menu_items mi join _stage s on s.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and not exists (select 1 from public.menu_item_links l where l.item_id = mi.id)")
    w("   ) as fuera_del_menu;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 9) Regla C — los que quedaron SIN TOCAR por nombre ambiguo.")
    w("--     Resuelvelos a mano (renombra o borra el repetido) y vuelve a correr")
    w("--     este script: al desaparecer la ambiguedad entran solos.")
    w("-- ---------------------------------------------------------------------------")
    w("select a.sku as sku_archivo, a.name as nombre_archivo, a.cat as categoria_archivo,")
    w("       a.price as precio_archivo,")
    w("       (select count(*) from _arch   a2 where a2.k = a.k) as veces_en_archivo,")
    w("       (select count(*) from _actual x2 where x2.k = a.k) as veces_en_catalogo,")
    w("       (select string_agg(x3.name, '  ||  ') from _actual x3 where x3.k = a.k) as filas_del_catalogo")
    w("from _arch a")
    w("where not exists (select 1 from _match m where m.sku = a.sku)")
    w("  and exists (select 1 from _actual x where x.k = a.k)")
    w("order by a.cat, a.name;")
    w("")
    w("commit;")
    w("")
    _out("import_products_528df61f.sql", o)


def _write_areas(items, n_bar, n_kit, n_both):
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- Áreas de producción — Business %s" % BID)
    w("-- Correr DESPUÉS de scripts/import_products_528df61f.sql")
    w("--")
    w("-- POR QUÉ HACE FALTA:")
    w("--   Un producto insertado por SQL queda con print_area_code = NULL. Sin área,")
    w("--   \"Enviar a cocina\" se bloquea y NO sale ninguna comanda — falla callado")
    w("--   hasta que alguien intenta imprimir.")
    w("--")
    w("-- ►► ANTES DE CORRER: pon abajo los CODES reales de las áreas del negocio.")
    w("--    Míralos con:  select code, name, is_active from public.print_areas")
    w("--                   where business_id = '%s';" % BID)
    w("--    Si un code no existe, el script aborta y te dice cuáles hay.")
    w("--")
    w("-- REPARTO:  cocina %d  |  bar %d  |  ambas %d (combos comida+bebida)" % (n_kit, n_bar, n_both))
    w("--   Las categorías de ofertas y días temáticos (OFERTAS HXH, MARTES TACOS")
    w("--   TUESDAY, SÁBADOS BOHEMIOS, …) mezclan comida y bebida, así que van")
    w("--   ruteadas producto por producto, no por categoría.")
    w("--")
    w("-- ESCRIBE LOS DOS MECANISMOS, A PROPÓSITO:")
    w("--   1. menu_item_print_areas (N:M) — fuente de verdad, permite 2 áreas.")
    w("--   2. menu_items.print_area_code (legacy) — NO es redundante:")
    w("--      fn_add_item_from_menu lo copia al order_item, y el lookup N:M se")
    w("--      salta entero sin red. Solo con N:M, un bache de red rutea mal.")
    w("--      En los combos de 2 áreas el legacy guarda la cocina (el plato).")
    w("--")
    w("-- CONVERGENTE: re-ejecutarlo deja el mismo estado.")
    w("-- =============================================================================")
    w("")
    w("begin;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- ►► 1) CODES DE LAS ÁREAS — AJUSTA ESTOS DOS VALORES")
    w("-- ---------------------------------------------------------------------------")
    w("create temp table _area_cfg (rol text primary key, code text) on commit drop;")
    w("insert into _area_cfg (rol, code) values")
    w("  ('K', 'cocina'),   -- área de COCINA")
    w("  ('B', 'bar');      -- área de BARRA")
    w("")
    w("do $$")
    w("declare")
    w("  v_business uuid := '%s';" % BID)
    w("  v_missing  text;")
    w("  v_have     text;")
    w("begin")
    w("  select string_agg(cfg.code, ', ')")
    w("    into v_missing")
    w("  from _area_cfg cfg")
    w("  where not exists (")
    w("    select 1 from public.print_areas a")
    w("    where a.business_id = v_business and a.code = cfg.code")
    w("      and coalesce(a.is_active, true)")
    w("  );")
    w("  if v_missing is not null then")
    w("    select string_agg(a.code || ' (' || a.name || ')', ', ' order by a.code)")
    w("      into v_have")
    w("    from public.print_areas a")
    w("    where a.business_id = v_business and coalesce(a.is_active, true);")
    w("    raise exception 'No existen estas áreas: %. El negocio tiene: %', v_missing, coalesce(v_have, '(ninguna)');")
    w("  end if;")
    w("end $$;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 2) Ruteo por sku -> area(s)")
    w("-- ---------------------------------------------------------------------------")
    w("create temp table _route (sku text primary key, areas text) on commit drop;")
    w("insert into _route (sku, areas) values")
    w(",\n".join("  (%s, '%s')" % (q(i["sku"]), i["area"]) for i in items) + ";")
    w("")
    w("-- Resolucion final: una fila por (producto, area) ya en UUIDs. Un 'KB'")
    w("-- produce dos. El lateral limit 1 evita duplicar si el negocio tuviera")
    w("-- dos areas con el mismo code.")
    w("create temp table _target on commit drop as")
    w("select mi.id as menu_item_id, a.id as print_area_id")
    w("from public.menu_items mi")
    w("join _route r on r.sku = mi.sku")
    w("join _area_cfg cfg on r.areas like '%' || cfg.rol || '%'")
    w("join lateral (")
    w("  select a2.id from public.print_areas a2")
    w("  where a2.business_id = mi.business_id and a2.code = cfg.code")
    w("    and coalesce(a2.is_active, true)")
    w("  order by a2.created_at asc limit 1")
    w(") a on true")
    w("where mi.business_id = '%s'::uuid;" % BID)
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 3) N:M — borra lo que sobra, inserta lo que falta")
    w("-- ---------------------------------------------------------------------------")
    w("delete from public.menu_item_print_areas mipa")
    w("using public.menu_items mi")
    w("join _route r on r.sku = mi.sku")
    w("where mipa.menu_item_id = mi.id")
    w("  and mi.business_id = '%s'::uuid" % BID)
    w("  and not exists (")
    w("    select 1 from _target t")
    w("    where t.menu_item_id = mipa.menu_item_id")
    w("      and t.print_area_id = mipa.print_area_id")
    w("  );")
    w("")
    w("insert into public.menu_item_print_areas (menu_item_id, print_area_id)")
    w("select t.menu_item_id, t.print_area_id from _target t")
    w("on conflict do nothing;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 4) Legacy print_area_code (en combos KB gana la cocina)")
    w("--    is_beverage = true solo para los que van SOLO a barra.")
    w("-- ---------------------------------------------------------------------------")
    w("update public.menu_items mi")
    w("set print_area_code = cfg.code,")
    w("    is_beverage     = (r.areas = 'B'),")
    w("    updated_at      = now()")
    w("from _route r")
    w("join _area_cfg cfg")
    w("  on cfg.rol = case when r.areas like '%K%' then 'K' else 'B' end")
    w("where mi.sku = r.sku")
    w("  and mi.business_id = '%s'::uuid" % BID)
    w("  and (mi.print_area_code is distinct from cfg.code")
    w("       or mi.is_beverage is distinct from (r.areas = 'B'));")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 5) Control. Esperado: sin_area_nm = 0, code_inexistente = 0.")
    w("--    catalogo_entero_sin_area cuenta TODO el negocio, incluidos los que el")
    w("--    archivo no trae: si sale > 0, esos productos no imprimen comanda.")
    w("-- ---------------------------------------------------------------------------")
    w("select")
    w("  (select count(*) from _route) as en_archivo,")
    w("  (select count(*) from public.menu_items mi join _route r on r.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and not exists (select 1 from public.menu_item_print_areas p where p.menu_item_id = mi.id)")
    w("   ) as sin_area_nm,")
    w("  (select count(*) from public.menu_items mi")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and mi.print_area_code is not null")
    w("      and not exists (select 1 from public.print_areas a")
    w("                       where a.business_id = mi.business_id and a.code = mi.print_area_code)")
    w("   ) as code_inexistente,")
    w("  (select count(*) from public.menu_items mi join _route r on r.sku = mi.sku")
    w("    where mi.business_id = '%s'::uuid and r.areas = 'KB') as combos_dos_areas," % BID)
    w("  (select count(*) from public.menu_items mi")
    w("    where mi.business_id = '%s'::uuid" % BID)
    w("      and coalesce(mi.print_area_code, '') = ''")
    w("      and not exists (select 1 from public.menu_item_print_areas p where p.menu_item_id = mi.id)")
    w("   ) as catalogo_entero_sin_area;")
    w("")
    w("commit;")
    w("")
    _out("seed_business_528df61f_print_areas.sql", o)


# -----------------------------------------------------------------------------
# Comparador: que del archivo ya existe en el negocio (match por nombre
# normalizado, porque los productos existentes NO tienen sku).
# -----------------------------------------------------------------------------
NORM = ("upper(btrim(regexp_replace("
        "translate(%s, 'ÁÉÍÓÚÜÑÀÈÌÒÙÂÊÎÔÛáéíóúüñàèìòùâêîôû', "
        "'AEIOUUNAEIOUAEIOUaeiouunaeiouaeiou'), '\\s+', ' ', 'g')))")


def _write_compare(items):
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- COMPARADOR — Business %s" % BID)
    w("--" )
    w("-- NO ESCRIBE NADA en las tablas de la app. Solo compara el archivo contra lo")
    w("-- que ya esta cargado y te dice que hacer con cada producto.")
    w("--")
    w("-- POR QUE HACE FALTA: el negocio ya tiene productos y NINGUNO tiene sku, asi")
    w("-- que el import (que matchea por sku) los duplicaria todos. Aqui el match es")
    w("-- por NOMBRE normalizado: mayusculas, sin acentos, espacios colapsados.")
    w("--")
    w("-- Devuelve 8 resultados:")
    w("--   1. Resumen de conteos")
    w("--   2. Nombres ambiguos: el mismo nombre repetido en el catalogo actual")
    w("--   3. Los del archivo que YA existen -> el import debe ACTUALIZARLOS")
    w("--   4. Los del archivo que NO existen -> se insertan nuevos")
    w("--   5. Los que ya estan cargados y NO vienen en el archivo -> tu decides")
    w("--   6. Como esta hoy el catalogo: tax_mode e impuestos enlazados")
    w("--   7. Nombres repetidos DENTRO del archivo")
    w("--   8. Categorias: cuales del archivo ya existen y cuales se crearian")
    w("-- =============================================================================")
    w("")
    w("begin;")
    w("")
    w("create temp table _stage (")
    w("  sku text primary key, name text, cat text, price numeric, cost numeric")
    w(") on commit drop;")
    w("")
    w("insert into _stage (sku, name, cat, price, cost) values")
    w(",\n".join(
        "  (%s, %s, %s, %s, %s)" % (q(i["sku"]), q(i["name"]), q(i["cat"]),
                                    num(i["price"]), num(i["cost"]))
        for i in items) + ";")
    w("")
    w("-- Catalogo actual del negocio, con el nombre normalizado.")
    w("create temp table _actual on commit drop as")
    w("select mi.id, mi.name, mi.price, mi.cost, mi.sku, mi.is_active,")
    w("       c.name as cat, %s as k" % (NORM % "mi.name"))
    w("from public.menu_items mi")
    w("left join public.categories c on c.id = mi.category_id")
    w("where mi.business_id = '%s'::uuid;" % BID)
    w("")
    w("-- Archivo, con el mismo nombre normalizado.")
    w("create temp table _arch on commit drop as")
    w("select s.*, %s as k from _stage s;" % (NORM % "s.name"))
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 1) Resumen")
    w("-- ---------------------------------------------------------------------------")
    w("select")
    w("  (select count(*) from _arch)   as en_archivo,")
    w("  (select count(*) from _actual) as ya_cargados,")
    w("  (select count(*) from _arch a where exists (select 1 from _actual x where x.k = a.k))")
    w("     as archivo_que_ya_existe,")
    w("  (select count(*) from _arch a where not exists (select 1 from _actual x where x.k = a.k))")
    w("     as archivo_nuevo,")
    w("  (select count(*) from _actual x where not exists (select 1 from _arch a where a.k = x.k))")
    w("     as cargado_que_no_viene_en_archivo,")
    w("  (select count(*) from (select k from _actual group by k having count(*) > 1) d)")
    w("     as nombres_ambiguos;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 2) Nombres repetidos en el catalogo ACTUAL (match ambiguo: hay que")
    w("--    resolverlos a mano antes de actualizar por nombre)")
    w("-- ---------------------------------------------------------------------------")
    w("select x.k as nombre_normalizado, count(*) as veces,")
    w("       string_agg(x.name || ' [' || coalesce(x.cat,'sin categoria') || ' | ' || x.price || ']', '  ||  ') as filas")
    w("from _actual x")
    w("group by x.k")
    w("having count(*) > 1")
    w("order by count(*) desc, x.k;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 3) YA EXISTEN — el import tiene que ACTUALIZAR estos, no insertarlos.")
    w("--    Mira las columnas *_cambia: te dice si el archivo trae otro dato.")
    w("-- ---------------------------------------------------------------------------")
    w("select a.sku            as sku_archivo,")
    w("       x.name           as nombre_actual,")
    w("       a.name           as nombre_archivo,")
    w("       x.price          as precio_actual,")
    w("       a.price          as precio_archivo,")
    w("       (x.price is distinct from a.price)                as precio_cambia,")
    w("       x.cat            as categoria_actual,")
    w("       a.cat            as categoria_archivo,")
    w("       (coalesce(x.cat,'') <> coalesce(a.cat,''))        as categoria_cambia,")
    w("       x.cost           as costo_actual,")
    w("       a.cost           as costo_archivo,")
    w("       x.is_active      as activo")
    w("from _arch a")
    w("join _actual x on x.k = a.k")
    w("order by (x.price is distinct from a.price) desc, a.cat, a.name;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 4) NUEVOS — no existen hoy, se insertarian")
    w("-- ---------------------------------------------------------------------------")
    w("select a.sku, a.name, a.cat, a.price, a.cost")
    w("from _arch a")
    w("where not exists (select 1 from _actual x where x.k = a.k)")
    w("order by a.cat, a.name;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 5) HUERFANOS — ya cargados pero NO vienen en el archivo.")
    w("--    Ojo: pueden ser productos vivos que el archivo simplemente no trae.")
    w("--    El import NO los toca; decides si los desactivas aparte.")
    w("-- ---------------------------------------------------------------------------")
    w("select x.id, x.name, x.cat, x.price, x.is_active")
    w("from _actual x")
    w("where not exists (select 1 from _arch a where a.k = x.k)")
    w("order by x.cat, x.name;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 6) Como esta HOY el catalogo: tax_mode e impuestos enlazados.")
    w("--    Si los existentes estan en 'inclusive', pasarlos a 'exclusive' cambia")
    w("--    el precio efectivo: hoy el impuesto va DENTRO, despues se suma encima.")
    w("-- ---------------------------------------------------------------------------")
    w("select mi.tax_mode,")
    w("       coalesce((select string_agg(t.name, '+' order by t.name)")
    w("                 from public.menu_item_taxes x join public.taxes t on t.id = x.tax_id")
    w("                 where x.item_id = mi.id), '(sin impuesto)') as impuestos,")
    w("       count(*) as productos")
    w("from public.menu_items mi")
    w("where mi.business_id = '%s'::uuid" % BID)
    w("group by 1, 2")
    w("order by productos desc;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 7) Nombres repetidos DENTRO del archivo. Algunos son productos distintos")
    w("--    de verdad (botella vs copa, con precio distinto); otros son basura del")
    w("--    POS viejo. Los que caigan en un nombre que ya existe en el catalogo")
    w("--    NO se cargan (regla C del import) hasta que decidas.")
    w("-- ---------------------------------------------------------------------------")
    w("select a.k as nombre_normalizado, count(*) as veces,")
    w("       string_agg(a.sku || ' [' || coalesce(a.cat,'?') || ' | ' || a.price || ']', '  ||  ' order by a.sku) as filas_del_archivo,")
    w("       exists (select 1 from _actual x where x.k = a.k) as ya_existe_en_catalogo")
    w("from _arch a")
    w("group by a.k")
    w("having count(*) > 1")
    w("order by a.k;")
    w("")
    w("-- ---------------------------------------------------------------------------")
    w("-- 8) Categorias del archivo vs las que ya existen")
    w("-- ---------------------------------------------------------------------------")
    w("select v.cat as categoria_archivo,")
    w("       (select count(*) from _arch a where a.cat = v.cat) as productos_en_archivo,")
    w("       exists (select 1 from public.categories c")
    w("               where c.business_id = '%s'::uuid and c.name = v.cat) as ya_existe" % BID)
    w("from (select distinct cat from _arch where cat is not null) v")
    w("order by ya_existe, v.cat;")
    w("")
    w("commit;")
    w("")
    _out("COMPARAR_catalogo_528df61f.sql", o)


def _write_resumen(items):
    """Todo el veredicto en UNA sola tabla, facil de copiar y pegar de vuelta."""
    o = []
    w = o.append
    w("-- =============================================================================")
    w("-- RESUMEN DE COMPARACION — Business %s" % BID)
    w("-- NO ESCRIBE NADA. Devuelve UNA sola tabla con todo el veredicto.")
    w("-- =============================================================================")
    w("")
    w("begin;")
    w("")
    w("create temp table _stage (sku text primary key, name text, cat text,")
    w("                          price numeric, cost numeric) on commit drop;")
    w("insert into _stage (sku, name, cat, price, cost) values")
    w(",\n".join(
        "  (%s, %s, %s, %s, %s)" % (q(i["sku"]), q(i["name"]), q(i["cat"]),
                                    num(i["price"]), num(i["cost"]))
        for i in items) + ";")
    w("")
    w("create temp table _arch on commit drop as")
    w("select s.*, %s as k from _stage s;" % (NORM % "s.name"))
    w("create temp table _actual on commit drop as")
    w("select mi.id, mi.name, mi.price, mi.tax_mode, %s as k" % (NORM % "mi.name"))
    w("from public.menu_items mi where mi.business_id = '%s'::uuid;" % BID)
    w("")
    w("select * from (")
    w("  select 1 as n, 'A. En el archivo'                        as concepto, (select count(*) from _arch)::text as valor")
    w("  union all select 2, 'B. Ya cargados en el negocio',      (select count(*) from _actual)::text")
    w("  union all select 3, '   -> del archivo, YA EXISTE (se actualiza)',")
    w("            (select count(*) from _arch a where exists (select 1 from _actual x where x.k = a.k))::text")
    w("  union all select 4, '   -> del archivo, NUEVO (se inserta)',")
    w("            (select count(*) from _arch a where not exists (select 1 from _actual x where x.k = a.k))::text")
    w("  union all select 5, '   -> AMBIGUO, no se toca',")
    w("            (select count(*) from _arch a")
    w("              where exists (select 1 from _actual x where x.k = a.k)")
    w("                and not ((select count(*) from _arch a2 where a2.k = a.k) = 1")
    w("                     and (select count(*) from _actual x2 where x2.k = a.k) = 1))::text")
    w("  union all select 6, '   -> cargados que el archivo NO trae',")
    w("            (select count(*) from _actual x where not exists (select 1 from _arch a where a.k = x.k))::text")
    w("  union all select 7, 'C. Catalogo quedaria en',")
    w("            ((select count(*) from _actual) +")
    w("             (select count(*) from _arch a where not exists (select 1 from _actual x where x.k = a.k)))::text")
    w("  union all select 8, 'D. Categorias: existen hoy',")
    w("            (select count(*) from public.categories where business_id = '%s'::uuid)::text" % BID)
    w("  union all select 9, '   -> se crearian',")
    w("            (select count(*) from (select distinct cat from _arch where cat is not null) v")
    w("              where not exists (select 1 from public.categories c")
    w("                where c.business_id = '%s'::uuid and c.name = v.cat))::text" % BID)
    w("  union all select 10, 'E. tax_mode del catalogo HOY: ' || t.tax_mode, t.cnt::text")
    w("            from (select tax_mode, count(*) cnt from _actual group by tax_mode) t")
    w("  union all select 11, 'F. Nombres repetidos DENTRO del archivo',")
    w("            (select count(*) from (select k from _arch group by k having count(*) > 1) d)::text")
    w("  union all select 12, 'G. Nombres repetidos en el catalogo actual',")
    w("            (select count(*) from (select k from _actual group by k having count(*) > 1) d)::text")
    w(") z order by n, concepto;")
    w("")
    w("commit;")
    w("")
    _out("RESUMEN_comparacion_528df61f.sql", o)


def _out(fname, lines):
    path = os.path.join(HERE, fname)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("escrito: %s" % path, file=sys.stderr)


if __name__ == "__main__":
    main()
