-- ============================================================================
-- Carga de productos → business c66824dd-6fa0-4a77-8c8f-76d9f2b262e3
-- Fuente: ListaDeProductos_24.06.2026 (export PDF, transcrito + limpiado).
--
-- price = PRECIO · cost = COSTO (0 si no había) · is_active = true
-- print_area_code: comida = 'kitchen_hot', bebida/bar = 'bar'
-- category_id se resuelve por NOMBRE (subquery).
--
-- EXCLUIDO (no son productos de catálogo):
--   * Categoría "Espalsa" (8/9/2025 … 16/9/2025) y "Servicios" (Letreros 150000)
--   * "Almueso/Almuerzo/Almueszo NN Junio" (especiales con fecha)
--   * "picadera para 8 criolla / 2 old parr / 1 jp" (nota de orden)
--
-- ⚠️  Viene de OCR: revisa precios/nombres contra el PDF. Si el destino ya
--    tiene productos, esto DUPLICA — confirma que esté vacío primero:
--      select count(*) from public.menu_items
--      where business_id = 'c66824dd-6fa0-4a77-8c8f-76d9f2b262e3';
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Categorías (NOT EXISTS para no duplicar)
-- ---------------------------------------------------------------------------
INSERT INTO public.categories (id, business_id, name, position, is_active, created_at)
SELECT gen_random_uuid(), 'c66824dd-6fa0-4a77-8c8f-76d9f2b262e3'::uuid, c.name, c.pos, true, now()
FROM (VALUES
  ('Empanadas',1),('Quipe',2),('Croquetas',3),('Bolas De Yuca',4),('Entradas',5),
  ('La Parillada',6),('Gfc Selección',7),('Pastas',8),('Risottos & Arroces',9),
  ('Pizzas',10),('Mariscos & Pescados',11),('Ny Street Food',12),('Green Bold',13),
  ('Desayunos',14),('Sopas Y Caldos',15),('Wrap',16),('Tacos',17),('Postres',18),
  ('Otros',19),('Combos',20),('Extras',21),('Gfc Garden Food Court',22),('CAFÉS',23),
  ('Frappes',24),('Té',25),('Chocolates',26),('Cocktails',27),('Gfc Selection',28),
  ('Champange Y Espumantes',29),('Vinos',30),('Vinos Blancos',31),('Vinos Rosado',32),
  ('España',33),('Italia',34),('Chile',35),('Estados Unidos',36),('Argentina',37),
  ('Francia',38),('España(rioja)',39),('Rivera Del Duero',40),('Italia.',41),
  ('Estados Unidos.',42),('Red Blends',43),('Cervezas',44),('Whiskys',45),
  ('Whiskys Trago',46),('Coñac',47),('Coñac Tragos',48),('Licores Y Digestivos',49),
  ('Vodka',50),('Vodka Tragos',51),('Tequila',52),('Tequila Tragos',53),('Ginebras',54),
  ('Ginebras Tragos',55),('Ron',56),('Ron Tragos',57),('Refrescos',58),('Bebida',59),
  ('Cigaros',60),('Brandy',61)
) AS c(name, pos)
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories x
  WHERE x.business_id = 'c66824dd-6fa0-4a77-8c8f-76d9f2b262e3'::uuid AND x.name = c.name
);

-- ---------------------------------------------------------------------------
-- 2) Productos
-- ---------------------------------------------------------------------------
INSERT INTO public.menu_items
  (id, business_id, category_id, name, price, cost, print_area_code, is_active)
SELECT
  gen_random_uuid(),
  'c66824dd-6fa0-4a77-8c8f-76d9f2b262e3'::uuid,
  (SELECT id FROM public.categories cat
     WHERE cat.business_id = 'c66824dd-6fa0-4a77-8c8f-76d9f2b262e3'::uuid
       AND cat.name = v.cat LIMIT 1),
  v.name, v.price, v.cost, v.area, true
FROM (VALUES
  -- (categoria, nombre, precio, costo, area)
  -- Empanadas
  ('Empanadas','Empanada De Pollo',180,0,'kitchen_hot'),
  ('Empanadas','Empanada De Res',180,0,'kitchen_hot'),
  ('Empanadas','Empanada De Res Y Queso',240,0,'kitchen_hot'),
  ('Empanadas','Empanada De Queso',180,0,'kitchen_hot'),
  ('Empanadas','Empanada Pollo A La Crema',270,0,'kitchen_hot'),
  ('Empanadas','Empanada De Pollo Y Queso',240,0,'kitchen_hot'),
  ('Empanadas','Empanada De Maduro Con Res',370,0,'kitchen_hot'),
  ('Empanadas','Empanada De Chivo',370,0,'kitchen_hot'),
  ('Empanadas','Empanada De Cielito Lindo',370,0,'kitchen_hot'),
  -- Quipe
  ('Quipe','Quipe De Res',180,0,'kitchen_hot'),
  ('Quipe','Quipe De Pollo',180,0,'kitchen_hot'),
  ('Quipe','Quipe De Queso',180,0,'kitchen_hot'),
  -- Croquetas
  ('Croquetas','Croquetas De Pollo',180,0,'kitchen_hot'),
  ('Croquetas','Croquetas De Pollo Y Chorizo',270,0,'kitchen_hot'),
  ('Croquetas','Croquetas De Cream Y Tocineta',270,0,'kitchen_hot'),
  -- Bolas De Yuca
  ('Bolas De Yuca','Bolas De Yuca Con Queso',180,0,'kitchen_hot'),
  ('Bolas De Yuca','Bola De Yuca Con Pollo',230,0,'kitchen_hot'),
  -- Entradas
  ('Entradas','Mofonguitos De Jabalí',550,0,'kitchen_hot'),
  ('Entradas','Mexican Dips',550,0,'kitchen_hot'),
  ('Entradas','Dip De Pollo',500,0,'kitchen_hot'),
  ('Entradas','Dip De Berenjena',500,0,'kitchen_hot'),
  ('Entradas','Rollitos De Berenjenas',450,0,'kitchen_hot'),
  ('Entradas','Churrasco Roll',650,0,'kitchen_hot'),
  ('Entradas','Rollitos De Pollo',450,0,'kitchen_hot'),
  ('Entradas','Canasticas De Jabali',550,0,'kitchen_hot'),
  ('Entradas','Mexdican Dips',550,0,'kitchen_hot'),
  ('Entradas','Rollito De Berengenas',450,0,'kitchen_hot'),
  ('Entradas','Longaniza',500,0,'kitchen_hot'),
  ('Entradas','Morsillas Burgalesa',375,0,'kitchen_hot'),
  ('Entradas','Nachos Mixtos',650,0,'kitchen_hot'),
  ('Entradas','Tabla De Embutidos',650,0,'kitchen_hot'),
  ('Entradas','Chicharron De Jabali',850,0,'kitchen_hot'),
  ('Entradas','Palito Mozzarela Stick',270,0,'kitchen_hot'),
  ('Entradas','Pechurina',350,0,'kitchen_hot'),
  ('Entradas','Casabe De La Casa',90,0,'kitchen_hot'),
  ('Entradas','Sadwich Gyro',500,0,'kitchen_hot'),
  ('Entradas','Canasticas De Camatones',650,0,'kitchen_hot'),
  ('Entradas','Brochetta',500,0,'kitchen_hot'),
  ('Entradas','Taco De Churrasco',550,0,'kitchen_hot'),
  ('Entradas','Dip De Espinacas',550,0,'kitchen_hot'),
  ('Entradas','Canasticas De Pollo',550,0,'kitchen_hot'),
  ('Entradas','Ceviche De Camarones',650,0,'kitchen_hot'),
  -- La Parillada
  ('La Parillada','Churrasco Angus',1800,0,'kitchen_hot'),
  ('La Parillada','Costillitas De Cerdo',750,0,'kitchen_hot'),
  ('La Parillada','Rib Eye',2100,0,'kitchen_hot'),
  ('La Parillada','Filete De Cerdo Al Grill',650,0,'kitchen_hot'),
  ('La Parillada','Taglita Al Estilo Gfc',1650,0,'kitchen_hot'),
  ('La Parillada','Cerdo Salado',450,0,'kitchen_hot'),
  ('La Parillada','Picaña',1950,0,'kitchen_hot'),
  ('La Parillada','Parrillada Asturiana',2300,0,'kitchen_hot'),
  ('La Parillada','T-Bone',2400,0,'kitchen_hot'),
  ('La Parillada','Wanyu Japones',4500,0,'kitchen_hot'),
  ('La Parillada','Plato Del Dia',250,0,'kitchen_hot'),
  ('La Parillada','Pechuga Al Grill',550,0,'kitchen_hot'),
  ('La Parillada','Picadera Mixta Criolla',1300,0,'kitchen_hot'),
  ('La Parillada','Alitas Al Grill 12 Piezas',800,0,'kitchen_hot'),
  ('La Parillada','Chuleta A La Plancha',400,0,'kitchen_hot'),
  ('La Parillada','Chicharron',450,0,'kitchen_hot'),
  ('La Parillada','Pollo Asado',550,0,'kitchen_hot'),
  ('La Parillada','1/2 Pollo Asado',300,0,'kitchen_hot'),
  ('La Parillada','Carne Salada',550,0,'kitchen_hot'),
  ('La Parillada','Tomahawk Angus',4500,0,'kitchen_hot'),
  ('La Parillada','Ribeye Angus',2400,0,'kitchen_hot'),
  ('La Parillada','Rib Eye Wagyu',4200,0,'kitchen_hot'),
  ('La Parillada','Churrasco Wagyu',3600,0,'kitchen_hot'),
  ('La Parillada','Pechuga A La Crema',600,0,'kitchen_hot'),
  ('La Parillada','Filete American Wanyu',2400,0,'kitchen_hot'),
  ('La Parillada','Filete De Res',900,0,'kitchen_hot'),
  -- Gfc Selección (comida)
  ('Gfc Selección','Pechuga Don Juan',650,0,'kitchen_hot'),
  ('Gfc Selección','Pechuga Don G',700,0,'kitchen_hot'),
  ('Gfc Selección','Tenderloin Don George',1400,0,'kitchen_hot'),
  ('Gfc Selección','Filete De Res Ibérico',850,0,'kitchen_hot'),
  ('Gfc Selección','Tacos De Jabali',550,0,'kitchen_hot'),
  ('Gfc Selección','Camarones Al Ajillo',650,0,'kitchen_hot'),
  ('Gfc Selección','Chivo Guisado',800,0,'kitchen_hot'),
  ('Gfc Selección','Churrasco Salad',1100,0,'kitchen_hot'),
  ('Gfc Selección','Menu ejecutivo',300,0,'kitchen_hot'),
  -- Pastas
  ('Pastas','Pasta A La Carbonara',400,0,'kitchen_hot'),
  ('Pastas','Pastas Gfc De Mar',1100,0,'kitchen_hot'),
  ('Pastas','Alfredo Camarones',600,0,'kitchen_hot'),
  ('Pastas','Alfredo Pollo',475,0,'kitchen_hot'),
  ('Pastas','Alfredo Salmon',800,0,'kitchen_hot'),
  ('Pastas','Alfredo',400,0,'kitchen_hot'),
  ('Pastas','Pasta 4 Quesos',550,0,'kitchen_hot'),
  ('Pastas','Raviolis De Espinacas Y Ricota',425,0,'kitchen_hot'),
  ('Pastas','Don Fernando',900,0,'kitchen_hot'),
  -- Risottos & Arroces
  ('Risottos & Arroces','Risoto Del Mar',1100,0,'kitchen_hot'),
  ('Risottos & Arroces','Rissoto De Churrasco',900,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Con Mariscos',950,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai Camarones',750,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai Pollo',550,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai',400,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai Lomo De Res',700,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai Cerdo',550,0,'kitchen_hot'),
  ('Risottos & Arroces','Arroz Thai Mixto Res Pollo Cerdo',700,0,'kitchen_hot'),
  ('Risottos & Arroces','Moro',100,0,'kitchen_hot'),
  -- Pizzas
  ('Pizzas','Pizza Cuatro Quesos Suprema',750,0,'kitchen_hot'),
  ('Pizzas','Pizza Pollo Al Pesto',750,0,'kitchen_hot'),
  ('Pizzas','Pizza Pepperoni Especial',750,0,'kitchen_hot'),
  ('Pizzas','Pizza Carnívora Suprema',800,0,'kitchen_hot'),
  ('Pizzas','Pizza Camarones',850,0,'kitchen_hot'),
  ('Pizzas','Pizza Chicharron',750,0,'kitchen_hot'),
  -- Mariscos & Pescados
  ('Mariscos & Pescados','Camarones Al Ajo & Cava',850,0,'kitchen_hot'),
  ('Mariscos & Pescados','Camarones Al Serrano',800,0,'kitchen_hot'),
  ('Mariscos & Pescados','Camarones Al Brass',750,0,'kitchen_hot'),
  ('Mariscos & Pescados','Mero Gfc',850,0,'kitchen_hot'),
  ('Mariscos & Pescados','Mero De Mediterraneo',1100,0,'kitchen_hot'),
  ('Mariscos & Pescados','Chillo Frito Lb',900,0,'kitchen_hot'),
  ('Mariscos & Pescados','Salmon Thai',875,0,'kitchen_hot'),
  ('Mariscos & Pescados','Salmon Al Oriental',800,0,'kitchen_hot'),
  ('Mariscos & Pescados','Camarones Asiatico',900,0,'kitchen_hot'),
  ('Mariscos & Pescados','Risoto De Churrasco',1200,0,'kitchen_hot'),
  ('Mariscos & Pescados','Mero A La Plancha',650,0,'kitchen_hot'),
  ('Mariscos & Pescados','Mero A La Criolla',650,0,'kitchen_hot'),
  ('Mariscos & Pescados','Mero A La Crema',650,0,'kitchen_hot'),
  ('Mariscos & Pescados','Langosta Al Thermidor',1350,0,'kitchen_hot'),
  ('Mariscos & Pescados','Langosta Al Ajillo',900,0,'kitchen_hot'),
  ('Mariscos & Pescados','Salmon Frutti Di Mare',1100,0,'kitchen_hot'),
  ('Mariscos & Pescados','Salpicon De Marisco',800,0,'kitchen_hot'),
  -- Ny Street Food
  ('Ny Street Food','Ny Burger',600,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa Gfc',550,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa Mexicana',650,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa De Pollo',500,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa Portobello',650,0,'kitchen_hot'),
  ('Ny Street Food','Philly Cheesesteak',700,0,'kitchen_hot'),
  ('Ny Street Food','El Italiano',700,0,'kitchen_hot'),
  ('Ny Street Food','Pastrami',650,0,'kitchen_hot'),
  ('Ny Street Food','Sandwich Blue Moon',550,0,'kitchen_hot'),
  ('Ny Street Food','HERO',500,0,'kitchen_hot'),
  ('Ny Street Food','HOT DOG TIME SQUARE',250,0,'kitchen_hot'),
  ('Ny Street Food','HOT DOG MEXICANO',300,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa Clasica',300,0,'kitchen_hot'),
  ('Ny Street Food','Hamburguesa Especial',350,0,'kitchen_hot'),
  ('Ny Street Food','Extra Carne De Hamburguesa',400,0,'kitchen_hot'),
  -- Green Bold
  ('Green Bold','Asian Salad',500,0,'kitchen_hot'),
  ('Green Bold','Asian Salad Camarones',750,0,'kitchen_hot'),
  ('Green Bold','Asian Salad Pollo',550,0,'kitchen_hot'),
  ('Green Bold','Cesar Gfc Camarones',750,0,'kitchen_hot'),
  ('Green Bold','Cesar Gfc Pollo',575,0,'kitchen_hot'),
  ('Green Bold','Mexican Bold',650,0,'kitchen_hot'),
  -- Desayunos
  ('Desayunos','Paninis Clásico De Jamón Y Queso',200,0,'kitchen_hot'),
  ('Desayunos','Paninis Mexicano',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Carne A La Parrilla',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Pollo Al Limón Y Ajo',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Atún',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Pollo Y Bacon',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Pollo Con Pesto',300,0,'kitchen_hot'),
  ('Desayunos','Paninis De Huevo Y Bacon',200,0,'kitchen_hot'),
  ('Desayunos','Paninis Caprese',300,0,'kitchen_hot'),
  ('Desayunos','Tostadas De Aguacate',250,0,'kitchen_hot'),
  ('Desayunos','Tostada Jamón Y Queso',180,0,'kitchen_hot'),
  ('Desayunos','Huevos Gfc',200,0,'kitchen_hot'),
  ('Desayunos','Omelette De Queso',200,0,'kitchen_hot'),
  ('Desayunos','Omelette De Jamón Y Queso',250,0,'kitchen_hot'),
  ('Desayunos','Omelette De Vegetales',200,0,'kitchen_hot'),
  ('Desayunos','Omelette Italiano',200,0,'kitchen_hot'),
  ('Desayunos','El Cibaeño',300,0,'kitchen_hot'),
  ('Desayunos','El Serrano',200,0,'kitchen_hot'),
  ('Desayunos','El Gringo',200,0,'kitchen_hot'),
  ('Desayunos','El Obrero',200,0,'kitchen_hot'),
  -- Sopas Y Caldos
  ('Sopas Y Caldos','Sopa De Marisco Mixta',1100,0,'kitchen_hot'),
  ('Sopas Y Caldos','Sopa De Vegetales',300,0,'kitchen_hot'),
  ('Sopas Y Caldos','Asopao De Camaron',700,0,'kitchen_hot'),
  ('Sopas Y Caldos','Sancocho',500,0,'kitchen_hot'),
  ('Sopas Y Caldos','Casuela De Mariscos',1100,0,'kitchen_hot'),
  ('Sopas Y Caldos','Sopa De Pollo',450,0,'kitchen_hot'),
  ('Sopas Y Caldos','Asopao De Pollo',550,0,'kitchen_hot'),
  ('Sopas Y Caldos','Sopa de nervio',300,0,'kitchen_hot'),
  ('Sopas Y Caldos','Sopa De Pescado',550,0,'kitchen_hot'),
  ('Sopas Y Caldos','Mondongo',550,0,'kitchen_hot'),
  -- Wrap
  ('Wrap','Mexican Wraps',650,0,'kitchen_hot'),
  ('Wrap','Asian Wraps',400,0,'kitchen_hot'),
  ('Wrap','Wraps Gfc',550,0,'kitchen_hot'),
  ('Wrap','Wraps Gfc Pollo',575,0,'kitchen_hot'),
  ('Wrap','Wraps Gfc Camarones',650,0,'kitchen_hot'),
  ('Wrap','Wrap De Pollo',475,0,'kitchen_hot'),
  ('Wrap','Wrap De Churrasco',800,0,'kitchen_hot'),
  ('Wrap','Riky Gfc',200,0,'kitchen_hot'),
  -- Tacos
  ('Tacos','Taco De Jabali',450,0,'kitchen_hot'),
  ('Tacos','Tacos De Camarones',650,0,'kitchen_hot'),
  ('Tacos','Tacos De Pollo',450,0,'kitchen_hot'),
  ('Tacos','Pasta De Salmon',750,0,'kitchen_hot'),
  ('Tacos','Tacos De Churrasco',650,0,'kitchen_hot'),
  -- Postres
  ('Postres','Postre Brauni A La Moda',350,0,'kitchen_hot'),
  ('Postres','Postre Tres Leche',450,0,'kitchen_hot'),
  ('Postres','Postre Quesillo Tradicional',300,0,'kitchen_hot'),
  ('Postres','Muffin De Chocolate',250,0,'kitchen_hot'),
  ('Postres','Mous De Chinola',250,0,'kitchen_hot'),
  ('Postres','Pudin',275,0,'kitchen_hot'),
  ('Postres','Cheesecake',350,0,'kitchen_hot'),
  -- Otros
  ('Otros','Sandwich De Pollo Gfc',550,0,'kitchen_hot'),
  ('Otros','Sandwich Don Jorge',550,0,'kitchen_hot'),
  ('Otros','Sandwich Supremo',600,0,'kitchen_hot'),
  ('Otros','Descorche',500,0,'bar'),
  ('Otros','Combo Cumpleanos BRUGAL',3000,0,'bar'),
  ('Otros','Combo Cumpleanos STOLI',3000,0,'bar'),
  ('Otros','Pizza Margarita Mediana',600,0,'kitchen_hot'),
  ('Otros','Chilindron',18000,0,'kitchen_hot'),
  ('Otros','Mofongo De Camarones',750,0,'kitchen_hot'),
  ('Otros','Descorche Whisky',1000,0,'bar'),
  ('Otros','Descorche Whisky 15 anos',2000,0,'bar'),
  ('Otros','Descorche Whisky 18 anos',3000,0,'bar'),
  ('Otros','Waffles',400,0,'kitchen_hot'),
  ('Otros','Mofongo De Chicharron',650,0,'kitchen_hot'),
  ('Otros','Mofongo De Pollo',575,0,'kitchen_hot'),
  ('Otros','Rabo',1000,0,'kitchen_hot'),
  ('Otros','Oferta Superbowl',1000,0,'kitchen_hot'),
  ('Otros','Vape',1000,0,'bar'),
  ('Otros','Platos Bufet',600,0,'kitchen_hot'),
  ('Otros','Paella Marinera',500,0,'kitchen_hot'),
  -- Combos
  ('Combos','Combo #1',800,0,'kitchen_hot'),
  ('Combos','Combo #2',400,0,'kitchen_hot'),
  ('Combos','Combo #3',500,0,'kitchen_hot'),
  ('Combos','Plato Bufet',5000,0,'kitchen_hot'),
  ('Combos','Bufet2',18700,0,'kitchen_hot'),
  ('Combos','Alitas 6 Combo Cubetazo',100,0,'kitchen_hot'),
  ('Combos','Combo Pollo Frito #2',300,0,'kitchen_hot'),
  ('Combos','Combo Pollo Frito #3',375,0,'kitchen_hot'),
  ('Combos','Combo Pollo Frito #4',450,0,'kitchen_hot'),
  -- Extras
  ('Extras','Extra Nacho',90,0,'kitchen_hot'),
  ('Extras','Extra Carne',100,0,'kitchen_hot'),
  ('Extras','Extra Berengena',90,0,'kitchen_hot'),
  ('Extras','Extra Canelones Rellenos',120,0,'kitchen_hot'),
  ('Extras','Extra Huevo',50,0,'kitchen_hot'),
  ('Extras','Extra Camarones',250,0,'kitchen_hot'),
  ('Extras','Extra Pechuga En Salsa Espinaca',150,0,'kitchen_hot'),
  ('Extras','Extra Vegetales',75,0,'kitchen_hot'),
  ('Extras','Extra Chorizo',50,0,'kitchen_hot'),
  ('Extras','Zumo De Limon',90,0,'bar'),
  ('Extras','Extra Tocineta',120,0,'kitchen_hot'),
  ('Extras','Extra Bechamel',100,0,'kitchen_hot'),
  ('Extras','Extra Cesar',100,0,'kitchen_hot'),
  ('Extras','Extra Pollo',150,0,'kitchen_hot'),
  ('Extras','Papa Frita',140,0,'kitchen_hot'),
  ('Extras','Frito Verde',150,0,'kitchen_hot'),
  ('Extras','Yuca Frita',140,0,'kitchen_hot'),
  ('Extras','Pure De Papa',150,0,'kitchen_hot'),
  ('Extras','Pure De Papa Gratinado',250,0,'kitchen_hot'),
  ('Extras','Pure De Yuca',150,0,'kitchen_hot'),
  ('Extras','Pure De Cepa Apio',150,0,'kitchen_hot'),
  ('Extras','Vegetales Al Gril',130,0,'kitchen_hot'),
  ('Extras','Vegetales Saltiados',180,0,'kitchen_hot'),
  ('Extras','Vegetales Al Vapor',180,0,'kitchen_hot'),
  ('Extras','Arroz Blanco',50,0,'kitchen_hot'),
  ('Extras','Habichuela',50,0,'kitchen_hot'),
  ('Extras','Papa Y Refresco',100,0,'kitchen_hot'),
  ('Extras','Ensalada Verde',90,0,'kitchen_hot'),
  ('Extras','Extra Pan',100,0,'kitchen_hot'),
  ('Extras','Guacamole/aguacate',50,0,'kitchen_hot'),
  ('Extras','Aceituna Extra',250,0,'kitchen_hot'),
  ('Extras','Extra Salsa Blue Chese',100,0,'kitchen_hot'),
  ('Extras','Picadera Centro Español',8200,0,'kitchen_hot'),
  ('Extras','Maduro',90,0,'kitchen_hot'),
  ('Extras','Arepas',50,0,'kitchen_hot'),
  ('Extras','Papa Sazonada',130,0,'kitchen_hot'),
  ('Extras','Ensalada De Rucula',120,0,'kitchen_hot'),
  ('Extras','Extra De Carne Salada',150,105,'kitchen_hot'),
  ('Extras','Entrada',500,0,'kitchen_hot'),
  ('Extras','Entrada Mil',1000,0,'kitchen_hot'),
  ('Extras','Ensalada De Aguacate',90,0,'kitchen_hot'),
  ('Extras','Servicio De Mani',250,0,'kitchen_hot'),
  ('Extras','Cherries',300,0,'kitchen_hot'),
  ('Extras','Cover',500,0,'kitchen_hot'),
  ('Extras','Extra Pepperoni',150,0,'kitchen_hot'),
  ('Extras','Platano Maduro',150,0,'kitchen_hot'),
  ('Extras','Salchicha De Desayuno',125,0,'kitchen_hot'),
  ('Extras','Salsa 4 Quesos',100,0,'kitchen_hot'),
  ('Extras','Frutas',250,0,'kitchen_hot'),
  ('Extras','Especies',150,0,'kitchen_hot'),
  ('Extras','Extra Licor',150,0,'bar'),
  ('Extras','Extra Queso',75,0,'kitchen_hot'),
  ('Extras','Berenjena Guisada',150,0,'kitchen_hot'),
  ('Extras','Guandules',70,0,'kitchen_hot'),
  ('Extras','Camarones A La Mariposa Salsa De Chinola',1250,0,'kitchen_hot'),
  -- Gfc Garden Food Court
  ('Gfc Garden Food Court','Almuerzo Especial',250,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Lasagna Especial',200,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Batida De Fresa',400,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Extra Alc',150,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Burrito Mixto',350,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Mofongo De Jabali',795,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Pastelon',250,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Taco De Res',450,0,'kitchen_hot'),
  ('Gfc Garden Food Court','Quesadilla',450,0,'kitchen_hot'),
  -- CAFÉS
  ('CAFÉS','Espresso',85,0,'bar'),
  ('CAFÉS','Cafe Americano',90,0,'bar'),
  ('CAFÉS','Cafe Don Nando',100,0,'bar'),
  ('CAFÉS','Cortado',100,0,'bar'),
  ('CAFÉS','Capuccino Italiano',165,0,'bar'),
  ('CAFÉS','Capuccino Americano',170,0,'bar'),
  ('CAFÉS','Caramel Capuccino',180,0,'bar'),
  ('CAFÉS','Capuccino French Vanilla',195,0,'bar'),
  ('CAFÉS','Capuccino Avellana',190,0,'bar'),
  ('CAFÉS','Marroccino',185,0,'bar'),
  ('CAFÉS','Moccacino',180,0,'bar'),
  ('CAFÉS','Mocha Mint',200,0,'bar'),
  ('CAFÉS','Latte',170,0,'bar'),
  ('CAFÉS','Lavanda Latte',200,0,'bar'),
  ('CAFÉS','Fogatta Latte',210,0,'bar'),
  ('CAFÉS','Baileys Coffee',200,0,'bar'),
  ('CAFÉS','Cafe Irlandes',200,0,'bar'),
  ('CAFÉS','Carajillo',200,0,'bar'),
  ('CAFÉS','Carajillo Agitado',210,0,'bar'),
  ('CAFÉS','Doppio (Doble Espreso)',160,0,'bar'),
  -- Frappes
  ('Frappes','Frappe De Caramelo',300,0,'bar'),
  ('Frappes','Frappe Chocolate',300,0,'bar'),
  ('Frappes','Frappe Cookies And Cream',315,0,'bar'),
  ('Frappes','Frappe De Mantequilla De Mani',300,0,'bar'),
  ('Frappes','Iced Latte',200,0,'bar'),
  -- Té
  ('Té','Frutos Del Bosque Y Flor De Jamaica',115,0,'bar'),
  ('Té','Te Verde Y Limoncillo',110,0,'bar'),
  ('Té','Matcha',165,0,'bar'),
  ('Té','Chai Tea',140,0,'bar'),
  -- Chocolates
  ('Chocolates','Chocolate Regular',115,0,'bar'),
  ('Chocolates','Chocolate Don Nando',170,0,'bar'),
  ('Chocolates','Chocolate Con Maiz',160,0,'bar'),
  ('Chocolates','Chocolate Con Ginger',160,0,'bar'),
  ('Chocolates','Chocolate Con Baileys',190,0,'bar'),
  -- Cocktails
  ('Cocktails','Mojito',450,0,'bar'),
  ('Cocktails','Mojito De Fresa',350,0,'bar'),
  ('Cocktails','Mojito De Coco',400,0,'bar'),
  ('Cocktails','Piña Colada Con Alcohol',375,0,'bar'),
  ('Cocktails','Sangrias',350,0,'bar'),
  ('Cocktails','Negroni Original',400,0,'bar'),
  ('Cocktails','Cosmopolitan',450,0,'bar'),
  ('Cocktails','Martinis',450,0,'bar'),
  ('Cocktails','Cuba Libre',275,0,'bar'),
  ('Cocktails','Margarita Patron',800,0,'bar'),
  ('Cocktails','Margarita De Limon',350,0,'bar'),
  ('Cocktails','Margarita De Fresa',450,0,'bar'),
  ('Cocktails','Margarita De Coco',450,0,'bar'),
  ('Cocktails','Margarita De Chinola',450,0,'bar'),
  ('Cocktails','Blue Agave',600,0,'bar'),
  ('Cocktails','Luchee Martini',492,0,'bar'),
  ('Cocktails','Caramel Y Coffee Martini',398,0,'bar'),
  ('Cocktails','Caipiriña',250,0,'bar'),
  ('Cocktails','Sangrtia Tinta',320,0,'bar'),
  ('Cocktails','Sangria Rosada',320,0,'bar'),
  ('Cocktails','Sangria Blanca',320,0,'bar'),
  ('Cocktails','Piña Colada Sin Alcohol',300,0,'bar'),
  ('Cocktails','Mojito De Chinola',400,0,'bar'),
  ('Cocktails','Mojito De Limon',400,0,'bar'),
  ('Cocktails','Mojito Especial 3/2',800,0,'bar'),
  ('Cocktails','Cardamon Rose Fizz',480,0,'bar'),
  ('Cocktails','Smoothie Fresa',150,0,'bar'),
  ('Cocktails','Ron Sour',300,0,'bar'),
  ('Cocktails','Trago Tequila Jose Cuervo',350,0,'bar'),
  ('Cocktails','Paloma',700,0,'bar'),
  ('Cocktails','Orgasmo',450,0,'bar'),
  ('Cocktails','Sex On The Beach',500,0,'bar'),
  ('Cocktails','Gin Tonic Afrutado',350,0,'bar'),
  ('Cocktails','Gin Tonic Especiado',350,0,'bar'),
  ('Cocktails','El Padrino',450,0,'bar'),
  ('Cocktails','Old Fashion',250,0,'bar'),
  ('Cocktails','Long Island',350,0,'bar'),
  ('Cocktails','Margarita 2x1',400,0,'bar'),
  ('Cocktails','2 X 1 Tacos',450,0,'bar'),
  -- Gfc Selection (cocktails, salvo 2 platos)
  ('Gfc Selection','Aperol Spritz',500,0,'bar'),
  ('Gfc Selection','Dark ''n'' Stormy',400,0,'bar'),
  ('Gfc Selection','Paper Plane',500,0,'bar'),
  ('Gfc Selection','Naked & Famous',700,0,'bar'),
  ('Gfc Selection','Jungle Bird',550,0,'bar'),
  ('Gfc Selection','Passion Paradise',550,0,'bar'),
  ('Gfc Selection','Lychee Martini',550,0,'bar'),
  ('Gfc Selection','La Red Rose Fizz',450,0,'bar'),
  ('Gfc Selection','Lavender Lemonade',550,0,'bar'),
  ('Gfc Selection','Pineapple Chili Margarita',650,0,'bar'),
  ('Gfc Selection','Passion Fruit Martini',600,0,'bar'),
  ('Gfc Selection','Salmon Caribeño',850,0,'kitchen_hot'),
  ('Gfc Selection','Salmon Al Grill',990,0,'kitchen_hot'),
  -- Champange Y Espumantes
  ('Champange Y Espumantes','Segura Viuda Rose',2200,0,'bar'),
  ('Champange Y Espumantes','Segura Viuda Brut',2200,0,'bar'),
  ('Champange Y Espumantes','Moet & Chandon Brut',6248.1,0,'bar'),
  ('Champange Y Espumantes','Moet & Chandon Imperial Ice',8900,0,'bar'),
  ('Champange Y Espumantes','Moet & Chandon Nectar Imperial Rose',8900,0,'bar'),
  ('Champange Y Espumantes','Cava Jp Chenet Ice',1600,610.17,'bar'),
  ('Champange Y Espumantes','Cava La Marca Prosseco',2200,0,'bar'),
  ('Champange Y Espumantes','Champagne Perrier Jouet Brut',7700,0,'bar'),
  ('Champange Y Espumantes','Aperol',2500,1012.71,'bar'),
  ('Champange Y Espumantes','Andre Rose',1600,0,'bar'),
  -- Vinos
  ('Vinos','Gotas De Mar',2700,0,'bar'),
  ('Vinos','Copa Vino Tinto',300,0,'bar'),
  ('Vinos','Vino 19 Crimes Red Blend',2400,0,'bar'),
  ('Vinos','Vino Six Eight Nine 689',1900,0,'bar'),
  ('Vinos','Vino Menague A Troix Cab. Sauvignon',1900,0,'bar'),
  ('Vinos','Vino Silk & Spice Red Blend',1690,0,'bar'),
  ('Vinos','Vino Palo Alto Reserva',1600,0,'bar'),
  ('Vinos','Vino Frontera Cab. Sauvignon',990,0,'bar'),
  ('Vinos','Vino 19 Crimes Martha Chard',2400,0,'bar'),
  ('Vinos','Protos Reserva',5500,0,'bar'),
  ('Vinos','Vino Santa Margheruta Pinot Grigio',2300,0,'bar'),
  ('Vinos','Vino Arzuaga La Planta',2200,0,'bar'),
  ('Vinos','Vino Primal Roots',1800,0,'bar'),
  ('Vinos','Vino Protos Crianza',4200,0,'bar'),
  ('Vinos','Vino Bogler Cab. Sauvignon',2300,0,'bar'),
  ('Vinos','Vino Frontera Merlot',1100,0,'bar'),
  ('Vinos','Vino Menague A Troix Red Wine',1900,1427.8,'bar'),
  ('Vinos','Vino Altos De Plato',1800,0,'bar'),
  ('Vinos','Vino Amarata Merlot',550,0,'bar'),
  ('Vinos','Vino Carmelo Rodero 9 Meses',2600,0,'bar'),
  ('Vinos','Vino The Show Cab. Sauvignon',2800,0,'bar'),
  ('Vinos','Vino Bogler Merlot',2800,0,'bar'),
  ('Vinos','Apothic Red',2100,0,'bar'),
  ('Vinos','Vino Emmolo Merlot',9000,0,'bar'),
  ('Vinos','Calvenet Cabernet Sauvugnon',950,0,'bar'),
  ('Vinos','Ramon Bilbao Crianza',1920,0,'bar'),
  ('Vinos','Vino Cune Rioja',1900,0,'bar'),
  -- Vinos Blancos
  ('Vinos Blancos','Vino Santiago Ruiz Albariño',2600,0,'bar'),
  ('Vinos Blancos','Copa Vino Blanco',300,0,'bar'),
  ('Vinos Blancos','Gotas De Mar Albariño',2400,0,'bar'),
  ('Vinos Blancos','Vino Protos Verdejo',2400,0,'bar'),
  ('Vinos Blancos','Lunardi Pinot Grigio',950,0,'bar'),
  ('Vinos Blancos','Cava Sin Alcohol',900,0,'bar'),
  -- Vinos Rosado
  ('Vinos Rosado','Decoy Rose Wine',2315.74,0,'bar'),
  ('Vinos Rosado','Muga Rose Wine',1799.5,0,'bar'),
  ('Vinos Rosado','Vino Beringer White Zinfander',1600,0,'bar'),
  ('Vinos Rosado','Copa Vino Rosado',250,0,'bar'),
  ('Vinos Rosado','Carlo Rose Rosado',900,330.51,'bar'),
  -- España
  ('España','Valduero Blanco',2584.2,0,'bar'),
  ('España','Protos Verdejo',1489,0,'bar'),
  -- Italia
  ('Italia','Santa Margherita Pinot Grigio',2042,0,'bar'),
  ('Italia','Cavit Moscato (Dulce)',1256.7,0,'bar'),
  -- Chile
  ('Chile','Santa Carolina Sauvignon Blanc Reservas',1233.69,0,'bar'),
  ('Chile','Santa Carolina Cabernet Sauvignon',1800,0,'bar'),
  ('Chile','Palo Alto Reserva I',1350,0,'bar'),
  ('Chile','Palo Alto Reserva Ii',1350,0,'bar'),
  -- Estados Unidos
  ('Estados Unidos','Menage A Trois Sauvignon Blanc',1336.3,0,'bar'),
  ('Estados Unidos','Kendal Jackson Sauvignon Blanc',2345.2,0,'bar'),
  -- Argentina
  ('Argentina','Finca El Origen Reservas Malbec',18001,0,'bar'),
  -- Francia
  ('Francia','Chateuneuf Du Pape La Fiole',3363,0,'bar'),
  ('Francia','Baron Philippe Mouton Cadet Reserva Medoc',2832,0,'bar'),
  -- España(rioja)
  ('España(rioja)','Marques De Caceres Crianza',1504.5,0,'bar'),
  ('España(rioja)','Marques De Caceres Reservas',2601.9,0,'bar'),
  ('España(rioja)','Glorioso Crianza',2584.2,0,'bar'),
  ('España(rioja)','Marques De Riscal Reservas',2699.25,0,'bar'),
  -- Rivera Del Duero
  ('Rivera Del Duero','Valduero Tierra Alta En Dos Maderas',3230.25,0,'bar'),
  ('Rivera Del Duero','Pago De Los Capellanes Crianza',3593.1,0,'bar'),
  ('Rivera Del Duero','Protos Crianza',2837.89,0,'bar'),
  ('Rivera Del Duero','Protos Reserva 5to. Ano',4557.75,0,'bar'),
  -- Italia.
  ('Italia.','Cavit Sweet Red',1345.2,0,'bar'),
  ('Italia.','Riporta Primitivo',1250,0,'bar'),
  -- Estados Unidos.
  ('Estados Unidos.','Robert Mondavi Private Selection',4572.49,0,'bar'),
  ('Estados Unidos.','Kendal Jackson Reservas Merlot',3244.99,0,'bar'),
  ('Estados Unidos.','Bonanza Cab. Sauv. Caymus Vineyards',2773,0,'bar'),
  ('Estados Unidos.','Belle Glos Pinot Noir',5973.75,0,'bar'),
  ('Estados Unidos.','Caymus Cabernet Sauvignon',10545.26,0,'bar'),
  -- Red Blends
  ('Red Blends','Menage A Trois Red Blend',1900,0,'bar'),
  ('Red Blends','Conundrum Red Blend',2758.25,0,'bar'),
  ('Red Blends','Bogle Essential Red',1976.5,0,'bar'),
  ('Red Blends','Decoy Red Wine',3407.25,0,'bar'),
  ('Red Blends','The Prisoner Red Wine',6932.5,0,'bar'),
  ('Red Blends','Play Time Red Blend',1725,0,'bar'),
  -- Cervezas
  ('Cervezas','Cerveza Presidente P Light',200,85.33,'bar'),
  ('Cervezas','Cerveza Presidente Normal P',200,0,'bar'),
  ('Cervezas','Cerveza One Peq',180,0,'bar'),
  ('Cervezas','Cerveza Heineken',250,118.64,'bar'),
  ('Cervezas','Cerveza Heineken 0.0',200,0,'bar'),
  ('Cervezas','Cerveza Paulanes Weissbier Rubia',350,0,'bar'),
  ('Cervezas','Cerveza Paulaner Dunkel',300,0,'bar'),
  ('Cervezas','Cerveza Coors Light',200,0,'bar'),
  ('Cervezas','Cerveza Paulaner Sin Alcohol',250,0,'bar'),
  ('Cervezas','Cerveza Modelo Rubia',250,0,'bar'),
  ('Cervezas','Cerveza 1906 Reserva Especial',170,0,'bar'),
  ('Cervezas','Cerveza Corona Cero',250,0,'bar'),
  ('Cervezas','Cerveza Erdinger Dunkel',290,0,'bar'),
  ('Cervezas','Cerveza Michelob',190,0,'bar'),
  ('Cervezas','Cerveza 8.6 Extreme',290,0,'bar'),
  ('Cervezas','Cerveza Desperado Red',190,0,'bar'),
  ('Cervezas','Cerveza La Chouffe',300,0,'bar'),
  ('Cervezas','Cerveza Extrella Galicia Especial',160,0,'bar'),
  ('Cervezas','Cerveza Paderborner Lata',170,0,'bar'),
  ('Cervezas','Cerveza Duvel',290,0,'bar'),
  ('Cervezas','Cerveza Dos Equis',200,0,'bar'),
  ('Cervezas','Cerveza Brude Hefeweizen',170,0,'bar'),
  ('Cervezas','Cerveza Dos Equis Ambar',190,0,'bar'),
  ('Cervezas','Cerveza Ocho Cero Nueve Lata',150,0,'bar'),
  ('Cervezas','Cerveza Birra Moretti',200,0,'bar'),
  ('Cervezas','Modelo Negra',250,0,'bar'),
  ('Cervezas','Cerveza Presidente Black',150,0,'bar'),
  ('Cervezas','Cerveza Corona',250,0,'bar'),
  ('Cervezas','Cerveza 5.0',180,0,'bar'),
  ('Cervezas','Cerveza Stella Artois',300,120.1,'bar'),
  ('Cervezas','Cerveza Blue Moon',300,0,'bar'),
  ('Cervezas','Cerveza Coors Original',250,0,'bar'),
  ('Cervezas','Especial Cerveza Corona 3/2',500,0,'bar'),
  ('Cervezas','Especial Cerveza Heineken 4/3',600,0,'bar'),
  ('Cervezas','Especial Cerveza Miller 4/3',600,0,'bar'),
  ('Cervezas','Cerveza 1906 Negra',195,0,'bar'),
  ('Cervezas','4/3 Paulaner Dunkel',900,0,'bar'),
  ('Cervezas','4/3 Paulaner Sin Alcohol',750,0,'bar'),
  ('Cervezas','3/2 Paulanes Sin Alcohol',500,0,'bar'),
  ('Cervezas','Cerveza Miller',195,0,'bar'),
  ('Cervezas','Cerveza Smirnoff Ice Rasberry',250,0,'bar'),
  ('Cervezas','Cerveza Smirnoff Ice Green Apple',250,0,'bar'),
  ('Cervezas','Cerveza Peroni',250,0,'bar'),
  ('Cervezas','Cerveza Republica',195,0,'bar'),
  ('Cervezas','Schnider Hell',350,0,'bar'),
  ('Cervezas','Schnider Tap 6',430,0,'bar'),
  ('Cervezas','Schnider Tap 7 Original',370,0,'bar'),
  ('Cervezas','Cerveza Sol',250,0,'bar'),
  ('Cervezas','Cerveza Smirnoff Original',250,127.12,'bar'),
  ('Cervezas','3 X 2 Michelob',400,0,'bar'),
  ('Cervezas','Especial De Presidente 3x2',400,0,'bar'),
  -- Whiskys
  ('Whiskys','Deep Eddy Strainht 750 Ml',1900,0,'bar'),
  ('Whiskys','Whisky Jhonny Walker 18 750 Ml',7900,0,'bar'),
  ('Whiskys','Whisky Buchanans 18 750 Ml',8750,0,'bar'),
  ('Whiskys','Whisky Glenfiddch',5300,0,'bar'),
  ('Whiskys','Whisky Johnnie Walker Black 750ml',4200,0,'bar'),
  ('Whiskys','Whisky Glenlivet 12',7000,3524,'bar'),
  ('Whiskys','Whisky Jack Daniels',2090,0,'bar'),
  ('Whiskys','Whisky Johnnie Walker Azul',24000,0,'bar'),
  ('Whiskys','Whisky Evan Williams',1900,0,'bar'),
  ('Whiskys','Whisky Botran 12',2600,0,'bar'),
  ('Whiskys','Whisky Njameson',2100,0,'bar'),
  ('Whiskys','Whisky Gidsons',1390,0,'bar'),
  ('Whiskys','Whisky The Deacon',3900,2256,'bar'),
  ('Whiskys','Whisky Ballantines 8 Anos',1690,907,'bar'),
  ('Whiskys','Whisky Beluga Noble',4900,0,'bar'),
  ('Whiskys','Whisky Ballentine 21 Anos',15900,10510,'bar'),
  ('Whiskys','Whisky Dewar 12',2400,0,'bar'),
  ('Whiskys','Whisky Chivas Regal 12',3800,0,'bar'),
  ('Whiskys','Whisky Johnnie Walker Gold Reserva',7000,4074,'bar'),
  ('Whiskys','Whisky Old Parr 12',4000,2168,'bar'),
  ('Whiskys','Whisky Old Parr 18',8500,4282.55,'bar'),
  ('Whiskys','Whisky The Macallan',8900,0,'bar'),
  ('Whiskys','Whisky Label 5 Gold',1900,0,'bar'),
  ('Whiskys','Whisky Scarlett Dark',1240,0,'bar'),
  ('Whiskys','Whisky Chivas Regal 15',6300,0,'bar'),
  ('Whiskys','Whisky Chivas 13',4700,0,'bar'),
  ('Whiskys','Whisky Johnnie Walker Double Black',6200,3279,'bar'),
  ('Whiskys','Whisky Glenfiddch 15',6900,0,'bar'),
  ('Whiskys','Whisky Johnnie Walker Gold 18',10500,4918,'bar'),
  ('Whiskys','Whiskey Ballantines 17',7900,4631,'bar'),
  ('Whiskys','Whisky Chivas Regal 18',10000,4849,'bar'),
  ('Whiskys','Whisky Glenlivet 15',7500,5149,'bar'),
  ('Whiskys','Whisky Glenlivet 18',13900,8295,'bar'),
  ('Whiskys','Whisky Buchannans 12 Años',4100,2644,'bar'),
  ('Whiskys','Whisky Black Label 12 Años 750ml',4200,2339,'bar'),
  ('Whiskys','Whisky Ballante 12 Años',3600,1891,'bar'),
  ('Whiskys','Whisky Glenfiddch 12',6000,2960,'bar'),
  ('Whiskys','Whisky Jameson',3600,1531,'bar'),
  ('Whiskys','Glenlivet Red Carribean Lt',4500,0,'bar'),
  ('Whiskys','Whisky Chivas Regal 21',25000,0,'bar'),
  ('Whiskys','Buchannan Master',5500,0,'bar'),
  ('Whiskys','Oferta Lunes Black',3500,0,'bar'),
  ('Whiskys','Extra Licor',150,0,'bar'),
  ('Whiskys','Don Julio 70',9000,0,'bar'),
  ('Whiskys','Whisky Botran 15 anos',3000,0,'bar'),
  ('Whiskys','Whisky Old Parr lt completo',4900,0,'bar'),
  ('Whiskys','Whisky Black Label 12 Años 1lt',6000,0,'bar'),
  -- Whiskys Trago
  ('Whiskys Trago','Trago The Glenlivet 12',590,0,'bar'),
  ('Whiskys Trago','Trago Johnnie Walker Gold',750,0,'bar'),
  ('Whiskys Trago','Trago Dewar 8 Anos',190,0,'bar'),
  ('Whiskys Trago','Trago Glenfiddch 12 Anos',400,0,'bar'),
  ('Whiskys Trago','Trago Chivas 13 Anos',350,0,'bar'),
  ('Whiskys Trago','Trago Chivas 15 Anos',750,0,'bar'),
  ('Whiskys Trago','Trago Chivas 18 Anos',900,0,'bar'),
  ('Whiskys Trago','Trago Glenlivet 15 Anos',600,0,'bar'),
  ('Whiskys Trago','Trago Johnnie Walker Azul',2200,0,'bar'),
  ('Whiskys Trago','Trago Old Parr 18 Anos',900,0,'bar'),
  ('Whiskys Trago','Trago Glendfiddch 15 Anos',490,0,'bar'),
  ('Whiskys Trago','Trago Buchannan 15 Anos',750,0,'bar'),
  ('Whiskys Trago','Trago Ballentines 8 Años',180,0,'bar'),
  ('Whiskys Trago','Trago Johnnie Gold Reserva',700,0,'bar'),
  ('Whiskys Trago','Trago Jameson 8 Anos',1490,0,'bar'),
  ('Whiskys Trago','Trago Chivas 12 Anos',300,0,'bar'),
  ('Whiskys Trago','Trago Johnnie 18 Anos',990,0,'bar'),
  ('Whiskys Trago','Trago Buchannans 18 Anos',990,0,'bar'),
  ('Whiskys Trago','Trago Johnnie Double Black',650,0,'bar'),
  ('Whiskys Trago','Trago Jack Daniels',220,0,'bar'),
  ('Whiskys Trago','Trago Old Parr Silver',690,0,'bar'),
  ('Whiskys Trago','Trago Buchannan 12 Anos',500,0,'bar'),
  ('Whiskys Trago','Trago Macallan 12 Anos',850,0,'bar'),
  ('Whiskys Trago','Trago Old Par 12 Años',450,0,'bar'),
  ('Whiskys Trago','Trago Jhonny 18',990,0,'bar'),
  ('Whiskys Trago','Trago Dewars 12 Años',390,0,'bar'),
  ('Whiskys Trago','Trago Black Label 12 Años',400,0,'bar'),
  ('Whiskys Trago','Doble Black',420,0,'bar'),
  ('Whiskys Trago','Trago Buchana Master',650,0,'bar'),
  ('Whiskys Trago','Trago Johnny Black',400,0,'bar'),
  ('Whiskys Trago','Trago Fireball',400,0,'bar'),
  ('Whiskys Trago','Trago White Label 12 Anos',450,0,'bar'),
  -- Coñac
  ('Coñac','Remy Martin Vsp',7800,0,'bar'),
  ('Coñac','Hennessy Vsop Lt',8000,0,'bar'),
  ('Coñac','Henessy V.s.',5500,0,'bar'),
  ('Coñac','Hennesy V.s',550,0,'bar'),
  -- Coñac Tragos
  ('Coñac Tragos','Trago Hennesy Vsop',800,0,'bar'),
  ('Coñac Tragos','Trago Remy Martin Vsop',650,0,'bar'),
  -- Licores Y Digestivos
  ('Licores Y Digestivos','Lt Limonchelo Celline',2100,0,'bar'),
  ('Licores Y Digestivos','Lt Licor 34',1090,0,'bar'),
  ('Licores Y Digestivos','Lt Licor 43',2300,0,'bar'),
  ('Licores Y Digestivos','Lt Amaro Averna',2100,0,'bar'),
  ('Licores Y Digestivos','Lt Campari',2050,0,'bar'),
  ('Licores Y Digestivos','Lt Fernet Branca',1900,0,'bar'),
  ('Licores Y Digestivos','Lt Kahlua',1800,0,'bar'),
  ('Licores Y Digestivos','Lt Lagrian Blue Curacao',900,0,'bar'),
  ('Licores Y Digestivos','Lagrian Crema De Menta',900,0,'bar'),
  ('Licores Y Digestivos','Lt Malibu Coco',2300,0,'bar'),
  ('Licores Y Digestivos','Lt Sambuca Romana',2400,0,'bar'),
  ('Licores Y Digestivos','Trago Limonchelo',300,0,'bar'),
  ('Licores Y Digestivos','Trago Sambuca',300,0,'bar'),
  ('Licores Y Digestivos','Trago Fernet Branca Menta',300,0,'bar'),
  ('Licores Y Digestivos','Cointreau',320,0,'bar'),
  ('Licores Y Digestivos','Trago Amaretto',300,0,'bar'),
  ('Licores Y Digestivos','Trago Frangelico',300,0,'bar'),
  ('Licores Y Digestivos','Trago Romana Sambucca',300,0,'bar'),
  ('Licores Y Digestivos','Liquor Lagran Blue Curacao',600,0,'bar'),
  ('Licores Y Digestivos','Amareto',600,585,'bar'),
  ('Licores Y Digestivos','Liquor Lagran Triple C',600,585,'bar'),
  ('Licores Y Digestivos','Liquor Royar Melocoton',500,400,'bar'),
  ('Licores Y Digestivos','Liquor Pareror',1300,1260,'bar'),
  ('Licores Y Digestivos','Liquor Midori',1400,1300,'bar'),
  ('Licores Y Digestivos','Liquor Wantor',1500,1351,'bar'),
  ('Licores Y Digestivos','Fernet Menta',1300,1270,'bar'),
  ('Licores Y Digestivos','Liquor 43',1200,1190,'bar'),
  ('Licores Y Digestivos','Recuerdo Mezcar',2603,2603,'bar'),
  ('Licores Y Digestivos','Liquor Ron 34',1600,780,'bar'),
  ('Licores Y Digestivos','Kahlua',1100,1100,'bar'),
  ('Licores Y Digestivos','Carolans',2800,980,'bar'),
  ('Licores Y Digestivos','Ciro Granadina',240,240,'bar'),
  ('Licores Y Digestivos','Grappa Nonito',2200,2200,'bar'),
  ('Licores Y Digestivos','Martini Gianco',580,758.47,'bar'),
  ('Licores Y Digestivos','Martini Rosso',580,580,'bar'),
  ('Licores Y Digestivos','Mantini Extra Dry',580,580,'bar'),
  ('Licores Y Digestivos','Disaronno Amaretto',3500,0,'bar'),
  -- Vodka
  ('Vodka','Lt Vodka Stolichnaya',2300,890,'bar'),
  ('Vodka','Lt Vodka Titos',2400,1585,'bar'),
  ('Vodka','Lt Vodka Absolut',2400,0,'bar'),
  ('Vodka','Lt Vodka Grey Goose',3800,1749,'bar'),
  ('Vodka','Lt Vodka Grey Goose Strawberry',3800,0,'bar'),
  ('Vodka','Lt Vodka Grey Goose Watermelon',3800,0,'bar'),
  ('Vodka','Vodka Grey Goose Orange',2900,0,'bar'),
  ('Vodka','Lt Vodka Poliakov',1270,0,'bar'),
  ('Vodka','Lt Vodka Ruskov',2400,0,'bar'),
  ('Vodka','Vodka Eristoff Lt',1600,709,'bar'),
  ('Vodka','Grey Goose Fresa',3200,1647,'bar'),
  ('Vodka','Grey Goose Sandy',3200,1747,'bar'),
  ('Vodka','Grey Goose Naranja',3200,1747,'bar'),
  -- Vodka Tragos
  ('Vodka Tragos','Trago Vodka Absolute',300,0,'bar'),
  ('Vodka Tragos','Trago Vodka Titos',290,0,'bar'),
  ('Vodka Tragos','Shot de Stoli',200,0,'bar'),
  -- Tequila
  ('Tequila','Tequila Don Julio Añejo',7500,0,'bar'),
  ('Tequila','Tequila Jose El Cuervo Blanco',2900,0,'bar'),
  ('Tequila','Tequila Altos Añejo',4300,0,'bar'),
  ('Tequila','Tequila Alto Plata',3600,0,'bar'),
  ('Tequila','Tequila Altos Plata Reposada',3600,0,'bar'),
  ('Tequila','Tequila Patron Sirve',5900,0,'bar'),
  ('Tequila','Tequila Patron Reposado',8000,3613,'bar'),
  ('Tequila','Mezcal El Recuerdo',3900,0,'bar'),
  ('Tequila','Tizcas Blanco',1490,0,'bar'),
  ('Tequila','Lunazul Blanco',3100,0,'bar'),
  ('Tequila','Tequila Don Julio 1942',25000,0,'bar'),
  ('Tequila','Tequila Patron Xo Cafe',6000,0,'bar'),
  ('Tequila','Tequila Don Julio Reposado',7500,0,'bar'),
  ('Tequila','Tequila Jose Cuervo Dorada',2900,0,'bar'),
  ('Tequila','Tequila Agabita Blanca',2200,0,'bar'),
  ('Tequila','Tequila Patron Platiniun',8500,0,'bar'),
  ('Tequila','Tequila Patron Silver',7000,3624,'bar'),
  ('Tequila','Altos Reposado',5000,2851,'bar'),
  ('Tequila','Altos Plata',5000,2329,'bar'),
  ('Tequila','Tequila 1800 Reposado',4500,0,'bar'),
  ('Tequila','Tequila 1800 Reposado Cristalino',7000,0,'bar'),
  ('Tequila','Shot Don Julio Reposado',450,0,'bar'),
  ('Tequila','Aguardiente',2900,0,'bar'),
  -- Tequila Tragos
  ('Tequila Tragos','Trago Tequila Patron Silver',700,0,'bar'),
  ('Tequila Tragos','Trago Tequila Don Julio Anejo',600,0,'bar'),
  ('Tequila Tragos','Trago Tequila Patron Reposado',800,0,'bar'),
  ('Tequila Tragos','Tequila Sunrise',350,0,'bar'),
  ('Tequila Tragos','Trago Don Julio Reposado',800,0,'bar'),
  ('Tequila Tragos','Trago Don Julio 1942',2500,0,'bar'),
  ('Tequila Tragos','Shot Tequila Agavita',250,0,'bar'),
  ('Tequila Tragos','2x1 Tequila Agavita',300,0,'bar'),
  ('Tequila Tragos','Shot Patron Silver',350,0,'bar'),
  ('Tequila Tragos','Shot Patron Reposado',400,0,'bar'),
  ('Tequila Tragos','Trago Patron Silver',700,0,'bar'),
  ('Tequila Tragos','Trago Patron Reposado',800,0,'bar'),
  -- Ginebras
  ('Ginebras','Lt Ginebra Beefeater Naranja',3200,1456,'bar'),
  ('Ginebras','Lt Ginebra Beefeater',2500,1350.88,'bar'),
  ('Ginebras','Lt Ginebra Bombay Saphire',3200,1517.6,'bar'),
  ('Ginebras','Lt Ginebra Brockmans',3900,2337,'bar'),
  ('Ginebras','Lt Ginebra Tanqueray',2699,0,'bar'),
  ('Ginebras','Brockmans Gin',6000,2337,'bar'),
  -- Ginebras Tragos
  ('Ginebras Tragos','Trago Ginebra Gibsons',300,0,'bar'),
  ('Ginebras Tragos','Trago Ginebra Tanqueray',300,0,'bar'),
  ('Ginebras Tragos','Trago Ginebra Brockmans',400,0,'bar'),
  ('Ginebras Tragos','Gin Tonic',300,0,'bar'),
  ('Ginebras Tragos','Trago Bombay Gin',300,0,'bar'),
  ('Ginebras Tragos','Trago Beefeater',300,0,'bar'),
  -- Ron
  ('Ron','Ron Brugal Extraviejo',1500,0,'bar'),
  ('Ron','Lt Ron Brugal 1888',4500,0,'bar'),
  ('Ron','Lt Ron Brugal Añejo',900,0,'bar'),
  ('Ron','Lt Ron Abuelo 12 Años',2900,0,'bar'),
  ('Ron','Lt Ron Abuelo 7 Años',1900,0,'bar'),
  ('Ron','Lt Ron Barcelo Gran Añejo',1600,585,'bar'),
  ('Ron','Lt Ron Barcelo Imperial',2900,1225,'bar'),
  ('Ron','Lt Ron Boltran 8 Años',3100,0,'bar'),
  ('Ron','Lt Ron Brugal Leyenda',3200,1195.93,'bar'),
  ('Ron','Lt Ron Brugal Triple Reserva',2100,926,'bar'),
  ('Ron','Lt Ron E.leon Jimenes',7500,5960,'bar'),
  ('Ron','Lt Ron Siboney 1920',1600,0,'bar'),
  ('Ron','Lt Ron Siboney Blanco',790,0,'bar'),
  ('Ron','Lt Brugal Doble Reserva',1800,889,'bar'),
  ('Ron','Ron Abuelo 12 Años',3800,2154.22,'bar'),
  ('Ron','Ron Abuelo Añejo',1700,905,'bar'),
  ('Ron','Ron Boltran 12 Años',2900,1434,'bar'),
  ('Ron','Ron Boltran 15 Años',3200,1826,'bar'),
  ('Ron','Ron E Leon Jimenez 110 Aniversario',7500,5680,'bar'),
  ('Ron','Brugal Xv Lt.',1400,580,'bar'),
  ('Ron','Extra Viejo Lt',1500,0,'bar'),
  ('Ron','Ron Brugal 1903 Lt',4500,0,'bar'),
  ('Ron','Trago Ron Brugal 1903',450,0,'bar'),
  -- Ron Tragos
  ('Ron Tragos','Trago Brugal Doble Reserva',250,0,'bar'),
  ('Ron Tragos','Trago Brugal Leyenda',300,0,'bar'),
  ('Ron Tragos','Trago Brughal Xv',200,0,'bar'),
  ('Ron Tragos','Trago Extra Viejo',200,0,'bar'),
  ('Ron Tragos','Trago Triple Reserva',300,0,'bar'),
  ('Ron Tragos','Trago Ron Brugal 1888',450,0,'bar'),
  ('Ron Tragos','Trago Sibone 1920',225,0,'bar'),
  ('Ron Tragos','Trago Barcelo Imperial',290,0,'bar'),
  ('Ron Tragos','Trago E Leon Jimenez 110 Aniversario',750,0,'bar'),
  -- Refrescos
  ('Refrescos','Agua Dasani',65,0,'bar'),
  ('Refrescos','Coca Cola',100,0,'bar'),
  ('Refrescos','Refresco Sprite',100,21.19,'bar'),
  ('Refrescos','Soda Amarga Canada Dry',75,29.66,'bar'),
  ('Refrescos','Soda Amarga Henrriquillo',75,0,'bar'),
  ('Refrescos','Agua Tonica',75,0,'bar'),
  ('Refrescos','Refresco Country Club Merengue',50,0,'bar'),
  ('Refrescos','Refresco Country Club Rojo',75,0,'bar'),
  ('Refrescos','Refresco Country Club Naranja',75,0,'bar'),
  ('Refrescos','Refresco Country Club Uva',75,0,'bar'),
  ('Refrescos','Agua Perrier Peq',200,0,'bar'),
  ('Refrescos','Agua Perrier Grande',350,0,'bar'),
  ('Refrescos','Agua San Pelegrino Peq',250,0,'bar'),
  ('Refrescos','Agua San Pellegrino Saborizada',200,0,'bar'),
  ('Refrescos','Agua Fiji 500 Ml',250,202,'bar'),
  ('Refrescos','Agua Icelandinc 500 Ml',150,0,'bar'),
  ('Refrescos','Red Bull',250,99.98,'bar'),
  ('Refrescos','Clamato',200,0,'bar'),
  ('Refrescos','Alitas Al Grill 6 Pieza',500,0,'kitchen_hot'),
  ('Refrescos','Agua De Coco Goya',250,0,'bar'),
  -- Bebida
  ('Bebida','Jugo Natural Limon',150,0,'bar'),
  ('Bebida','Jugo Natural Cereza',120,0,'bar'),
  ('Bebida','Jugo Natural Chinola',175,0,'bar'),
  ('Bebida','Jugo Natural Chinola Avena',120,0,'bar'),
  ('Bebida','Jugo Manzana 4 Oz',125,0,'bar'),
  ('Bebida','Smoothie De Limon',150,0,'bar'),
  ('Bebida','Jugo Pina 4 Oz',70,0,'bar'),
  ('Bebida','Jugo Mott Grande',400,0,'bar'),
  ('Bebida','Jugo Natural Naranja',180,0,'bar'),
  ('Bebida','Jugo De Fresa',150,0,'bar'),
  ('Bebida','Jugo De Manzana Mediano',150,0,'bar'),
  ('Bebida','Jugo Natural De Pina',120,0,'bar'),
  ('Bebida','Jugo De Cranberry 4 Oz',200,0,'bar'),
  ('Bebida','Frozen De Chinola',200,0,'bar'),
  ('Bebida','Frozen De Limon',250,0,'bar'),
  ('Bebida','Agua Panna 500 Ml',175,0,'bar'),
  ('Bebida','Trago Jameson',350,0,'bar'),
  ('Bebida','Jugo De Cereza',150,0,'bar'),
  ('Bebida','Trago Stolinaya',300,0,'bar'),
  ('Bebida','Michelada',300,0,'bar'),
  ('Bebida','Coca Cola Zero',75,0,'bar'),
  ('Bebida','Mimosa',250,0,'bar'),
  ('Bebida','Espresso Martini',300,0,'bar'),
  ('Bebida','Frut Ponch',150,0,'bar'),
  ('Bebida','Canada Dry Ginger Ale',75,0,'bar'),
  ('Bebida','Karma',170,0,'bar'),
  ('Bebida','Daiquiris',350,0,'bar'),
  ('Bebida','Agua S Bernrdo Mineral Sparkling 500ml',250,0,'bar'),
  ('Bebida','Agua S Bernardo Spring Water',150,0,'bar'),
  ('Bebida','Agua Icelandic 8.4 Aagua Mineral 750ml',350,0,'bar'),
  ('Bebida','Agua Icelandic 8.4 Agua Mineral 500ml',250,0,'bar'),
  ('Bebida','Agua Icelandic Gasificada Sabores',190,0,'bar'),
  ('Bebida','Agua Icelandic Lata',150,0,'bar'),
  ('Bebida','Schneider Weisse Original',300,0,'bar'),
  ('Bebida','Schneider Weisse Helles',300,0,'bar'),
  ('Bebida','Schneider Weisse Aventinus',350,0,'bar'),
  ('Bebida','Extra Parmesano',90,0,'bar'),
  ('Bebida','Trago Cardenal Mendoza',500,0,'bar'),
  ('Bebida','Red Rock',60,0,'bar'),
  ('Bebida','Jugo Mott 4 Onz',200,0,'bar'),
  ('Bebida','Trago grey goose',450,0,'bar'),
  ('Bebida','Café Con Leche',125,0,'bar'),
  ('Bebida','Disaronno Amaretto',3500,0,'bar'),
  ('Bebida','Jugo De Piña De Trago',250,0,'bar'),
  ('Bebida','Mori Soñando Naranja',250,0,'bar'),
  ('Bebida','Mori Soñando Limon',250,0,'bar'),
  ('Bebida','Mori Soñando Chinola',250,0,'bar'),
  ('Bebida','Bacardi Gold',1100,0,'bar'),
  ('Bebida','Piña Colada Blue',450,0,'bar'),
  ('Bebida','Icelandic Agua Grande',300,0,'bar'),
  ('Bebida','Descorche Tequila',1500,0,'bar'),
  ('Bebida','Fruit Punch',850,0,'bar'),
  ('Bebida','Trago Malibu',300,0,'bar'),
  ('Bebida','Sidra',400,0,'bar'),
  ('Bebida','Trago de Baileys',300,0,'bar'),
  ('Bebida','Botella de Baileys',3000,0,'bar'),
  ('Bebida','Trago Disaronno Amaretto',600,0,'bar'),
  ('Bebida','Agua',75,0,'bar'),
  ('Bebida','Leche',50,0,'bar'),
  ('Bebida','Sangria Jarra',1200,0,'bar'),
  -- Cigaros
  ('Cigaros','La Aurora 107 Nicaragua',430,0,'bar'),
  ('Cigaros','La Aurora 1945 Don Bme',430,0,'bar'),
  ('Cigaros','La Aurora Connecticut',380,0,'bar'),
  ('Cigaros','La Aurora Maduro Robusto',300,0,'bar'),
  ('Cigaros','La Aurora 120 Aniversario',600,0,'bar'),
  ('Cigaros','Cigarrillo Electronico',1000,0,'bar'),
  ('Cigaros','Cigarrillo Electronico Electrico',1000,0,'bar'),
  -- Brandy
  ('Brandy','Cardenal Mendoza',7900,3600,'bar')
) AS v(cat, name, price, cost, area);

COMMIT;
