  ('ENTRADAS', 'Fuego Callejero',                     285.00,  1),
  -- "Brisa tropical" choca con el cóctel Brisa Tropical ($375) de COCTELES.
  ('ENTRADAS', 'Brisa Tropical (Entrada)',            295.00,  2),
  ('ENTRADAS', 'Cóctel de Camarones',                 390.00,  3),
  ('ENTRADAS', 'Croquetas de Plátano Maduro',         390.00,  4),
  ('ENTRADAS', 'Nachos',                              425.00,  5),
  ('ENTRADAS', 'Deditos de Mozzarella',               295.00,  6),
  ('ENTRADAS', 'Bastoncito de Pescado',               350.00,  7),
  ('ENTRADAS', 'Croquetas de Pollo',                  275.00,  8),

  ('ESPECIALES DE LA CASA Y PASTAS', 'Pasta Tropical',                     595.00,  1),
  ('ESPECIALES DE LA CASA Y PASTAS', 'Pasta al Fuego Azotea',              450.00,  2),
  ('ESPECIALES DE LA CASA Y PASTAS', 'Pechuga a la Casa',                  725.00,  3),
  ('ESPECIALES DE LA CASA Y PASTAS', 'Camarones al Fuego Tropical Azotea', 750.00,  4),
  ('ESPECIALES DE LA CASA Y PASTAS', 'Filete de Cerdo Mignon',             795.00,  5),

  ('CARNES', 'Filete de Res a la Plancha',            1150.00, 1),
  ('CARNES', 'Filete Mar y Tierra',                   1250.00, 2),
  ('CARNES', 'Filete Miñón',                          1150.00, 3),
  ('CARNES', 'Churrasco Angus',                       1650.00, 4),
  ('CARNES', 'Solomillo de Res',                      1050.00, 5),
  ('CARNES', 'Costilla de Res',                        650.00, 6),
  ('CARNES', 'Picaña',                                1250.00, 7),
  ('CARNES', 'T-Bone al Grill',                       2895.00, 8),
  ('CARNES', 'Filete de Chuleta',                      550.00, 9),

  ('POLLO', 'Pechuga a la Crema',                      580.00,  1),
  ('POLLO', 'Pechuga de Pollo',                        450.00,  2),
  ('POLLO', 'Pechuga Cordon Bleu',                     590.00,  3),
  ('POLLO', 'Pechuga Salteada',                        425.00,  4),
  ('POLLO', 'Brocheta de Pollo',                       395.00,  5),
  ('POLLO', 'Pechuga de Pollo al Vino Blanco',         595.00,  6),
  ('POLLO', 'Pechuga al Hongo',                        650.00,  7),
  ('POLLO', 'Alitas',                                  375.00,  8),
  ('POLLO', 'Alitas Búfalo',                           325.00,  9),
  ('POLLO', 'Alita Asiática',                          295.00, 10),

  ('MOFONGOS', 'Mofongo de Camarones',                 550.00,  1),
  ('MOFONGOS', 'Mofongo de Pollo',                     495.00,  2),
  ('MOFONGOS', 'Mofongo Mixto',                        650.00,  3),
  ('MOFONGOS', 'Mofongo de Chicharrón',                595.00,  4),

  ('MARISCOS, PESCADOS Y CHIVO', 'Camarones al Grill',                 695.00, 1),
  ('MARISCOS, PESCADOS Y CHIVO', 'Salmón al Grill',                    950.00, 2),
  ('MARISCOS, PESCADOS Y CHIVO', 'Filete de Mero en Salsa de Chinola', 590.00, 3),
  ('MARISCOS, PESCADOS Y CHIVO', 'Chivo Guisado',                      950.00, 4),
  ('MARISCOS, PESCADOS Y CHIVO', 'Chivo al Vino',                      950.00, 5),
  ('MARISCOS, PESCADOS Y CHIVO', 'Chivo al Horno',                     950.00, 6),

  ('ENSALADAS', 'Ensalada César',                      480.00,  1),
  ('ENSALADAS', 'César Mar y Tierra',                  690.00,  2),
  ('ENSALADAS', 'Rosette a la Casa',                   595.00,  3),
  ('ENSALADAS', 'Indonsa con Parisienne de Camarones', 695.00,  4),

  ('SOPAS', 'Sopa de Pollo',                           350.00,  1),
  ('SOPAS', 'Sopa de Camarones',                       650.00,  2),
  ('SOPAS', 'Sopa de Mero',                            495.00,  3),

  ('GUARNICIONES', 'Puré de Papa',                     125.00,  1),
  ('GUARNICIONES', 'Tostones',                         125.00,  2),
  ('GUARNICIONES', 'Papa Salteada',                    125.00,  3),
  ('GUARNICIONES', 'Arroz Blanco',                     100.00,  4),
  ('GUARNICIONES', 'Vegetales Salteados',               95.00,  5),
  ('GUARNICIONES', 'Vegetales Hervidos',                95.00,  6),
  ('GUARNICIONES', 'Batata Frita',                      95.00,  7)
